function varargout = vsc_mtdc_cpf_vsc_capability_event(op, varargin)
%VSC_MTDC_CPF_VSC_CAPABILITY_EVENT VSC capability CPF event utilities.

switch lower(op)
    case 'record'
        varargout{1} = event_record(varargin{:});
    case 'complete'
        varargout{1} = complete_event(varargin{:});
    case 'lambda'
        [varargout{1:nargout}] = event_lambda(varargin{:});
    otherwise
        error('vsc_mtdc_cpf_vsc_capability_event:unknown_op', ...
            'Unknown VSC capability event utility ''%s''.', op);
end


function ev = event_record(event_k, event_idx, msg, report)
ev = struct('k', event_k, 'name', 'VSC_CAPABILITY', ...
    'idx', event_idx, 'msg', msg, ...
    'vsc_idx', report.changed_idx, ...
    'lambda_event', report.lambda_event, ...
    'lambda_candidate', report.lambda_candidate, ...
    'lambda_previous', report.lambda_previous, ...
    'event_location_method', {report.event_location_method}, ...
    'P_candidate', report.P, 'Q_candidate', report.Q, ...
    'V_candidate', report.V, ...
    'margin_candidate', report.margin_candidate, ...
    'margin_previous', report.margin_previous, ...
    'previous_margin_error', {report.previous_margin_error}, ...
    'margin_event', report.margin_event, ...
    'active_limit', {report.active_limit}, ...
    'projection_mode', {report.projection_mode}, ...
    'policy_reason', {report.policy_reason}, ...
    'target_ac_mode_if_saturated', ...
        report.target_ac_mode_if_saturated, ...
    'P_projected', report.P_saturated, ...
    'Q_projected', report.Q_saturated, ...
    'S_projected', report.S_saturated, ...
    'from_ac_mode', report.from_mode, ...
    'to_ac_mode', report.to_mode, ...
    'Smax', report.Smax, 'Vmax', report.Vmax, ...
    'Smax_source', {report.Smax_source}, ...
    'Vmax_source', {report.Vmax_source}, ...
    'mode_source', {report.mode_source}, ...
    'P_final', [], 'Q_final', [], 'V_final', [], ...
    'margin_final', [], 'inside_final', [], 'final_error', {{}});


function ev = complete_event(ev, report, vsc, baseMVA)
c = idx_vsc;
n = length(report.changed_idx);
P_final = NaN(n, 1);
Q_final = NaN(n, 1);
V_final = NaN(n, 1);
margin_final = NaN(n, 1);
inside_final = false(n, 1);
final_error = repmat({''}, n, 1);
for ii = 1:n
    k = report.changed_idx(ii);
    if size(vsc, 1) < k || size(vsc, 2) < c.QAC
        continue;
    end
    P_final(ii) = vsc(k, c.PAC);
    Q_final(ii) = vsc(k, c.QAC);
    V_final(ii) = capability_voltage(vsc, k, c);
    try
        [sat_final, ~, ~, ~, info_final] = vsc_capability_curve( ...
            P_final(ii), Q_final(ii), report.Smax(ii), ...
            V_final(ii), vsc(k, :), report.projection_mode{ii}, ...
            report.Vmax(ii), baseMVA);
        margin_final(ii) = info_final.margin;
        inside_final(ii) = ~sat_final;
    catch me
        final_error{ii} = me.message;
    end
end
ev.P_final = P_final;
ev.Q_final = Q_final;
ev.V_final = V_final;
ev.margin_final = margin_final;
ev.inside_final = inside_final;
ev.final_error = final_error;


function [lam_event, margin_event, method] = event_lambda( ...
        lam_prev, lam_candidate, margin_prev, margin_candidate)
lam_event = lam_candidate;
margin_event = margin_candidate;
method = 'candidate';
if isfinite(lam_prev) && isfinite(lam_candidate) && ...
        isfinite(margin_prev) && isfinite(margin_candidate) && ...
        lam_candidate ~= lam_prev && margin_prev >= 0 && ...
        margin_candidate < 0
    den = margin_prev - margin_candidate;
    if den > 0
        alpha = margin_prev / den;
        lam_event = lam_prev + alpha * (lam_candidate - lam_prev);
        margin_event = 0;
        method = 'linear_margin';
    end
end


function V = capability_voltage(vsc, row, c)
if size(vsc, 2) >= c.VAC_PCC && ...
        isfinite(vsc(row, c.VAC_PCC)) && vsc(row, c.VAC_PCC) > 0
    V = vsc(row, c.VAC_PCC);
elseif size(vsc, 2) >= c.VAC_INTERNAL && ...
        isfinite(vsc(row, c.VAC_INTERNAL)) && ...
        vsc(row, c.VAC_INTERNAL) > 0
    V = vsc(row, c.VAC_INTERNAL);
else
    V = vsc(row, c.VAC_SET);
end
