function varargout = vsc_mtdc_cpf_gen_capability_event(op, varargin)
%VSC_MTDC_CPF_GEN_CAPABILITY_EVENT Generator capability CPF event utilities.

switch lower(op)
    case 'record'
        varargout{1} = event_record(varargin{:});
    case 'complete'
        varargout{1} = complete_event(varargin{:});
    otherwise
        error('vsc_mtdc_cpf_gen_capability_event:unknown_op', ...
            'Unknown generator capability event utility ''%s''.', op);
end


function ev = event_record(event_k, event_idx, msg, report)
ev = struct('k', event_k, 'name', 'GEN_CAPABILITY', ...
    'idx', event_idx, 'msg', msg, ...
    'gen_idx', report.changed_idx, ...
    'bus', report.bus, ...
    'lambda_event', report.lambda_event, ...
    'lambda_candidate', report.lambda_candidate, ...
    'lambda_previous', report.lambda_previous, ...
    'event_location_method', {report.event_location_method}, ...
    'P_candidate', report.P, 'Q_candidate', report.Q, ...
    'margin_candidate', report.margin_candidate, ...
    'margin_previous', report.margin_previous, ...
    'previous_margin_error', {report.previous_margin_error}, ...
    'margin_event', report.margin_event, ...
    'active_limit', {report.active_limit}, ...
    'P_projected', report.P_saturated, ...
    'Q_projected', report.Q_saturated, ...
    'S_projected', report.S_saturated, ...
    'Smax', report.Smax, ...
    'gen_type_code', report.gen_type_code, ...
    'gen_type', {report.gen_type}, ...
    'bisection_iterations', report.bisection_iterations, ...
    'location_error', {report.location_error}, ...
    'P_final', [], 'Q_final', [], 'V_final', [], ...
    'margin_final', [], 'inside_final', [], 'final_error', {{}});


function ev = complete_event(ev, report, bus, gen)
[~, ~, ~, ~, BUS_I, ~, ~, ~, ~, ~, ~, VM] = idx_bus;
[GEN_BUS, PG, QG] = idx_gen;
n = length(report.changed_idx);
P_final = NaN(n, 1);
Q_final = NaN(n, 1);
V_final = NaN(n, 1);
margin_final = NaN(n, 1);
inside_final = false(n, 1);
final_error = repmat({''}, n, 1);
for ii = 1:n
    g = report.changed_idx(ii);
    if size(gen, 1) < g
        continue;
    end
    P_final(ii) = gen(g, PG);
    Q_final(ii) = gen(g, QG);
    row = find(bus(:, BUS_I) == gen(g, GEN_BUS), 1);
    if ~isempty(row)
        V_final(ii) = bus(row, VM);
    end
    [sat_final, margin_final(ii), final_error{ii}] = ...
        gen_capability_margin(gen, g, report.Smax(ii), ...
        report.gen_type_code(ii), PG, QG);
    inside_final(ii) = ~sat_final;
end
ev.P_final = P_final;
ev.Q_final = Q_final;
ev.V_final = V_final;
ev.margin_final = margin_final;
ev.inside_final = inside_final;
ev.final_error = final_error;


function [sat, margin, err] = gen_capability_margin( ...
        gen, g, Smax, type, PG, QG)
sat = 0;
margin = NaN;
err = '';
if size(gen, 1) < g
    err = 'result does not contain requested generator row';
    return;
end
try
    [sat, ~, ~, ~, info] = gen_capability_curve( ...
        gen(g, PG), gen(g, QG), Smax, type);
    margin = info.margin;
catch me
    err = me.message;
end
