function t_vsc_mtdc(quiet)
% t_vsc_mtdc - Tests for AC/DC VSC-MTDC power flow.

%   MATPOWER
%   Copyright (c) 2026, Power Systems Engineering Research Center (PSERC)
%
%   This file is part of MATPOWER.
%   Covered by the 3-clause BSD License (see LICENSE file for details).
%   See https://matpower.org for more info.

if nargin < 1
    quiet = 0;
end

num_tests = 328;

t_begin(num_tests, quiet);

%% define named indices into data matrices
[PQ, ~, REF, ~, BUS_I, BUS_TYPE, PD, QD, ~, BS, ~, VM, VA] = idx_bus;
[F_BUS, T_BUS, BR_R, BR_X, ~, ~, ~, ~, TAP, ~, BR_STATUS, PF, QF, ~, QT] = idx_brch;
[GEN_BUS, PG, QG, QMAX, ~, ~, ~, GEN_STATUS] = idx_gen;
c = idx_vsc;
bdc = idx_busdc;
brdc = idx_branchdc;

mpopt = mpoption('out.all', 0, 'verbose', 0);
mpopt_seq = mpopt;
mpopt_seq.vsc_mtdc.method = 'sequential';
mpopt_u = mpopt;
mpopt_u.vsc_mtdc.method = 'unified';

%%-----  2-terminal VSC-MTDC case  -----
mpc2 = loadcase('case3_vsc_mtdc_2term');
active2 = find(mpc2.vsc(:, c.VSC_STATUS) > 0);
Gdc = makeGdc(mpc2.busdc, mpc2.branchdc);
t_is(full(Gdc), [100 -100; -100 100], 12, 'makeGdc ignores out-of-service DC branch');

[r2, success] = runpf_vsc_mtdc(mpc2, mpopt_seq);
t_ok(success, '2-terminal VSC-MTDC PF success');
t_ok(r2.iterations > 0 && r2.iterations <= 20, '2-terminal iteration count');
t_is(r2.vsc(active2, c.PAC) + r2.vsc(active2, c.PDC) + r2.vsc(active2, c.PLOSS), ...
    zeros(length(active2), 1), 6, '2-terminal VSC power balance');
t_is(r2.busdc(:, bdc.VDC), [1; 1.0049752469181], 8, '2-terminal DC voltages');
slack2 = find(r2.vsc(:, c.IS_DC_SLACK) > 0);
t_is(slack2, 1, 12, '2-terminal DC slack identification');
t_ok(abs(r2.vsc(slack2, c.PDC) - mpc2.vsc(slack2, c.PDC_SET)) > 1, ...
    '2-terminal slack Pdc is calculated result');
t_is(r2.branchdc(2, brdc.PFDC:brdc.ITDC), zeros(1, 4), 12, ...
    'out-of-service DC branch ignored');
t_is(r2.vsc(3, [c.PAC c.QAC c.PDC c.PLOSS c.FILTER_BUS c.INTERNAL_BUS]), ...
    zeros(1, 6), 12, 'out-of-service VSC ignored');
t_ok(all(r2.vsc(active2, c.PLOSS) > 0), '2-terminal VSC losses are positive');

t_is(size(r2.ac.bus, 1), size(mpc2.bus, 1) + 2 * length(active2), 12, ...
    '2-terminal auxiliary AC buses');
t_is(size(r2.ac.branch, 1), size(mpc2.branch, 1) + 2 * length(active2), 12, ...
    '2-terminal transformer and reactor branches');
t_is(r2.vsc(active2, c.FILTER_BUS), [4; 6], 12, '2-terminal filter bus numbering');
t_is(r2.vsc(active2, c.INTERNAL_BUS), [5; 7], 12, '2-terminal internal bus numbering');
t_is(r2.ac.branch(r2.vsc(1, c.TR_BRANCH), BR_R:BR_X), ...
    mpc2.vsc(1, c.TR_R:c.TR_X), 12, 'transformer branch keeps own impedance');
t_is(r2.ac.branch(r2.vsc(1, c.TR_BRANCH), TAP), 0, 12, ...
    'converter station transformer has no tap');
t_is(r2.ac.branch(r2.vsc(1, c.REACTOR_BRANCH), BR_R:BR_X), ...
    mpc2.vsc(1, c.REACTOR_R:c.REACTOR_X), 12, 'reactor branch keeps own impedance');
frow = find(r2.ac.bus(:, BUS_I) == r2.vsc(1, c.FILTER_BUS), 1);
t_is(r2.ac.bus(frow, BS), mpc2.vsc(1, c.FILTER_B) * mpc2.baseMVA, 12, ...
    'filter shunt is on filter bus');
equiv = find(r2.ac.branch(:, F_BUS) == mpc2.vsc(1, c.VSC_BUS) & ...
             r2.ac.branch(:, T_BUS) == r2.vsc(1, c.INTERNAL_BUS) & ...
             r2.ac.branch(:, BR_STATUS) > 0, 1);
t_ok(isempty(equiv), 'no transformer plus reactor equivalent branch');

%%-----  VSC-MTDC savecase round-trip  -----%%
mpc2_save = mpc2;
mpc2_save.vsc_capability = struct('Snom', [70 80 90], ...
    'VconvMax', [1.15 1.15 1.15]);
mpc2_save.vsc_hvdc_dispatch = struct('policy', 'constant', ...
    'delta_pd', 0, ...
    'delta_pdc_set', zeros(size(mpc2.vsc, 1), 1));
mpc2_save.cpf_policies = struct('lambda_definition', 'load_scaling_only');
fn_vsc = sprintf('vsc_mtdc_savecase_test_%d', fix(1e8*rand));
savecase(fn_vsc, mpc2_save);
txt_vsc = fileread([fn_vsc '.m']);
mpc2_rt = loadcase(fn_vsc);
delete([fn_vsc '.m']);
t_ok(~isempty(strfind(txt_vsc, 'mpc.busdc = [')) && ...
    ~isempty(strfind(txt_vsc, 'mpc.branchdc = [')) && ...
    ~isempty(strfind(txt_vsc, 'mpc.vsc = [')), ...
    'savecase writes VSC-MTDC matrices');
t_is(mpc2_rt.busdc, mpc2.busdc, 12, ...
    'savecase/loadcase preserves busdc');
t_is(mpc2_rt.branchdc, mpc2.branchdc, 12, ...
    'savecase/loadcase preserves branchdc');
t_is(mpc2_rt.vsc, mpc2.vsc, 12, ...
    'savecase/loadcase preserves vsc');
t_is(mpc2_rt.vsc_capability.Snom, mpc2_save.vsc_capability.Snom, 12, ...
    'savecase/loadcase preserves VSC capability metadata');
t_str_match(mpc2_rt.vsc_hvdc_dispatch.policy, 'constant', ...
    'savecase/loadcase preserves VSC/HVDC dispatch policy');
t_is(mpc2_rt.vsc_hvdc_dispatch.delta_pdc_set, ...
    mpc2_save.vsc_hvdc_dispatch.delta_pdc_set, 12, ...
    'savecase/loadcase preserves VSC/HVDC dispatch vectors');
t_str_match(mpc2_rt.cpf_policies.lambda_definition, ...
    'load_scaling_only', ...
    'savecase/loadcase preserves CPF incremental policy metadata');
[~, success] = runpf_vsc_mtdc(mpc2_rt, mpopt_u);
t_ok(success, 'savecase/loadcase VSC-MTDC case can be re-solved');

fn_pf = sprintf('vsc_mtdc_pf_solvedcase_test_%d', fix(1e8*rand));
[~, success] = runpf_vsc_mtdc(mpc2, mpopt_u, '', fn_pf);
mpc2_pf_rt = loadcase(fn_pf);
delete([fn_pf '.m']);
t_ok(success && isfield(mpc2_pf_rt, 'busdc') && ...
    isfield(mpc2_pf_rt, 'branchdc') && isfield(mpc2_pf_rt, 'vsc'), ...
    'runpf_vsc_mtdc solvedcase preserves VSC-MTDC fields');
[~, success] = runpf_vsc_mtdc(mpc2_pf_rt, mpopt_u);
t_ok(success, 'runpf_vsc_mtdc solvedcase can be re-solved');

%%-----  3-terminal VSC-MTDC case  -----
mpc3 = loadcase('case5_vsc_mtdc_3term');
active3 = find(mpc3.vsc(:, c.VSC_STATUS) > 0);
[r3, success] = runpf_vsc_mtdc(mpc3, mpopt_seq);
t_ok(success, '3-terminal VSC-MTDC PF success');
t_ok(r3.iterations > 0 && r3.iterations <= 20, '3-terminal iteration count');
t_is(r3.vsc(active3, c.PAC) + r3.vsc(active3, c.PDC) + r3.vsc(active3, c.PLOSS), ...
    zeros(length(active3), 1), 6, '3-terminal VSC power balance');
t_is(r3.busdc(:, bdc.VDC), [1; 1.00482815597738; 1.00451086157824], 8, ...
    '3-terminal DC voltages');
t_ok(r3.vsc(1, c.PDC) < 0, '3-terminal slack absorbs DC power');
t_is(sum(r3.vsc(active3, c.PDC)), ...
    sum(r3.branchdc(:, brdc.PFDC) + r3.branchdc(:, brdc.PTDC)), 8, ...
    '3-terminal DC injections equal DC branch losses');
t_ok(abs(r3.vsc(1, c.PDC) - mpc3.vsc(1, c.PDC_SET)) > 1, ...
    '3-terminal slack Pdc is calculated result');
t_is(r3.vsc(2:3, c.PDC), [35; 20], 10, '3-terminal Pdc controls hold set points');
t_is(r3.vsc(1, c.VAC_PCC), mpc3.vsc(1, c.VAC_SET), 8, ...
    'VSC AC voltage control holds PCC voltage');
t_is(r3.vsc(2:3, c.QAC), [0; 0], 8, 'VSC fixed Q controls hold set points');
t_is(size(r3.ac.bus, 1), size(mpc3.bus, 1) + 2 * length(active3), 12, ...
    '3-terminal auxiliary AC buses');
t_is(r3.vsc(4, [c.PAC c.QAC c.PDC c.PLOSS c.FILTER_BUS c.INTERNAL_BUS]), ...
    zeros(1, 6), 12, '3-terminal out-of-service VSC ignored');
[r3u, success] = runpf_vsc_mtdc(mpc3, mpopt_u);
t_ok(success, '3-terminal unified VSC-MTDC PF success');
t_is(r3u.vsc(active3, [c.PAC c.QAC c.PDC c.VDC c.VAC_PCC c.VAC_INTERNAL c.PLOSS]), ...
    r3.vsc(active3, [c.PAC c.QAC c.PDC c.VDC c.VAC_PCC c.VAC_INTERNAL c.PLOSS]), ...
    6, '3-terminal unified VSC results match sequential solution');
t_is(r3u.vsc(4, [c.PAC c.QAC c.PDC c.PLOSS c.FILTER_BUS c.INTERNAL_BUS]), ...
    zeros(1, 6), 12, '3-terminal unified out-of-service VSC ignored');

%%-----  Beerten 5-bus paper validation case  -----
mpcb = loadcase('case5_vsc_mtdc_beerten');
[rb, success] = runpf_vsc_mtdc(mpcb, mpopt_seq);
t_ok(success, 'Beerten 5-bus VSC-MTDC PF success');
t_ok(rb.iterations > 0 && rb.iterations <= 20, 'Beerten iteration count');

paper_bus = [
    1   1.060    0.00;
    2   1.000   -2.39;
    3   1.000   -3.90;
    4   0.996   -4.27;
    5   0.991   -4.15;
];
got_bus = zeros(size(paper_bus, 1), 2);
for kk = 1:size(paper_bus, 1)
    row = find(rb.ac.bus(:, BUS_I) == paper_bus(kk, 1), 1);
    got_bus(kk, :) = rb.ac.bus(row, [VM VA]);
end
t_ok(max(abs(got_bus(:, 1) - paper_bus(:, 2))) < 1e-3, ...
    'Beerten AC voltage magnitudes match published table');
t_ok(max(abs(got_bus(:, 2) - paper_bus(:, 3))) < 1e-2, ...
    'Beerten AC voltage angles match published table');

paper_vsc = [
    2   0.984   -3.760   -60.00   -40.00   0.05   2.08   1.36   -58.59   1.008;
    3   1.003   -3.431    20.68     7.17   0.00   0.19   1.15    21.84   1.000;
    5   0.993   -3.340    35.00     5.00   0.01   0.51   1.19    36.21   0.998;
];
got_uc = rb.vsc(:, c.VAC_INTERNAL);
got_delta_c = zeros(size(rb.vsc, 1), 1);
got_reactor_q = zeros(size(rb.vsc, 1), 1);
for kk = 1:size(rb.vsc, 1)
    row = find(rb.ac.bus(:, BUS_I) == rb.vsc(kk, c.INTERNAL_BUS), 1);
    got_delta_c(kk) = rb.ac.bus(row, VA);
    br = rb.vsc(kk, c.REACTOR_BRANCH);
    got_reactor_q(kk) = rb.ac.branch(br, QF) + rb.ac.branch(br, QT);
end
t_ok(max(abs(got_uc - paper_vsc(:, 2))) < 2e-3, ...
    'Beerten converter internal voltages match published table');
t_ok(max(abs(got_delta_c - paper_vsc(:, 3))) < 2e-2, ...
    'Beerten converter internal angles match published table');
t_ok(max(abs(rb.vsc(:, c.PAC) - paper_vsc(:, 4))) < 0.1, ...
    'Beerten converter active powers match published table');
t_ok(max(abs(rb.vsc(:, c.QAC) - paper_vsc(:, 5))) < 0.5, ...
    'Beerten converter reactive powers match published table');
t_ok(max(abs(rb.vsc(:, c.PREACTOR_LOSS) - paper_vsc(:, 6))) < 0.01, ...
    'Beerten station active losses match published table');
t_ok(max(abs(got_reactor_q - paper_vsc(:, 7))) < 0.08, ...
    'Beerten reactor reactive losses match published table');
t_ok(max(abs(rb.vsc(:, c.PLOSS) - paper_vsc(:, 8))) < 0.05, ...
    'Beerten converter losses match published table');
t_ok(max(abs(-rb.vsc(:, c.PDC) - paper_vsc(:, 9))) < 0.1, ...
    'Beerten DC powers match published table sign convention');
t_ok(max(abs(rb.vsc(:, c.VDC) - paper_vsc(:, 10))) < 1e-3, ...
    'Beerten DC voltages match published table');
t_is(rb.vsc(:, c.PAC) + rb.vsc(:, c.PDC) + rb.vsc(:, c.PLOSS), ...
    zeros(size(rb.vsc, 1), 1), 6, 'Beerten VSC power balance');

[ru, success] = runpf_vsc_mtdc(mpcb, mpopt_u);
t_ok(success, 'Beerten unified VSC-MTDC PF success');
t_ok(ru.iterations > 0 && ru.iterations <= 10, 'Beerten unified iteration count');
t_str_match(ru.convergence.jacobian, 'analytic', ...
    'unified VSC-MTDC PF uses analytic Jacobian');
rdef = runpf_vsc_mtdc(mpcb, mpopt);
t_str_match(rdef.convergence.method, 'unified', ...
    'runpf_vsc_mtdc defaults to unified method');
t_is(ru.vsc(:, [c.PAC c.QAC c.PDC c.VDC c.VAC_PCC c.VAC_INTERNAL c.PLOSS]), ...
    rb.vsc(:, [c.PAC c.QAC c.PDC c.VDC c.VAC_PCC c.VAC_INTERNAL c.PLOSS]), ...
    6, 'Beerten unified VSC results match sequential solution');
t_is(ru.ac.bus(1:size(mpcb.bus, 1), [VM VA]), ...
    rb.ac.bus(1:size(mpcb.bus, 1), [VM VA]), ...
    6, 'Beerten unified AC voltages match sequential solution');
[rpsse_pf_u, success] = runpf_psse(mpcb, mpopt_u);
t_ok(success, 'runpf_psse delegates unified VSC-MTDC PF successfully');
t_str_match(rpsse_pf_u.psse.pf.task_class, 'unified_vsc_mtdc', ...
    'runpf_psse reports unified VSC-MTDC PF task class');
t_str_match(rpsse_pf_u.convergence.jacobian, 'analytic', ...
    'runpf_psse unified VSC-MTDC PF uses analytic Jacobian');
t_ok(rpsse_pf_u.convergence.psse_aware, ...
    'runpf_psse unified VSC-MTDC PF is PSS/E-aware');
t_ok(~isempty(strfind(rpsse_pf_u.psse.pf.formulation, 'PSS/E-aware unified')), ...
    'runpf_psse reports PSS/E-aware unified formulation');

%%-----  TESIS-style capability helpers and post-solve audit  -----
[sat_g, Pg, Qg] = gen_capability_curve(35, 10, 100, 'thermal');
t_is([sat_g Pg Qg], [0 35 10], 12, ...
    'thermal generator capability leaves interior point unchanged');
[sat_g, Pg, Qg] = gen_capability_curve(40, 10, 100, 'hydraulic');
t_is([sat_g Pg Qg], [0 40 10], 12, ...
    'hydraulic generator capability leaves interior point unchanged');
[sat_g, Pg, Qg] = gen_capability_curve(40, 10, 100, 'wind');
t_is([sat_g Pg Qg], [0 40 10], 12, ...
    'wind generator capability leaves interior point unchanged');
[sat_g, Pg, Qg, ~, info_g] = gen_capability_curve(40, 95, 100, 'thermal');
q0_g = (80^2 - 80^2 - 60^2) / (2 * 80 - 2 * 60);
s0_g = 80 - q0_g;
t_is([sat_g Pg Qg], [1 40 sqrt(s0_g^2 - 40^2) + q0_g], 10, ...
    'thermal generator capability saturates to expected arc point');
t_str_match(info_g.active_limit, 'overexcited_arc', ...
    'generator capability audits active limit');
t_is([info_g.element_base_mva info_g.P_original_pu ...
    info_g.Q_original_pu info_g.Smax_pu], [100 0.4 0.95 1], 12, ...
    'generator capability uses own MVA base');

[sat_v, Pv, Qv] = vsc_capability_geometry(0.20, 0.05, 1, 1, 0.5, 'radial');
t_is([sat_v Pv Qv], [0 0.20 0.05], 12, ...
    'VSC capability leaves interior point unchanged');
[sat_v, Pv, ~, ~, info_vp] = ...
    vsc_capability_geometry(1.30, 0.05, 1, 1, 0.5, 'radial');
t_ok(sat_v && info_vp.violated_p && abs(Pv) <= info_vp.pMax + 1e-10, ...
    'VSC capability saturates outside |P| limit');
[sat_v, Pv, Qv, ~, info_vi] = ...
    vsc_capability_geometry(0.60, -1.20, 1, 1, 0.5, 'radial');
t_is([sat_v Pv Qv], [1 0.60 / hypot(0.60, -1.20) ...
    -1.20 / hypot(0.60, -1.20)], 10, ...
    'VSC capability saturates outside AC current limit');
t_ok(info_vi.violated_current && ~info_vi.violated_p, ...
    'VSC capability audits AC current limit');
[sat_v, Pv, Qv, ~, info_vv] = ...
    vsc_capability_geometry(0.20, 0.80, 1, 1, 0.5, 'radial');
t_ok(sat_v && info_vv.violated_voltage, ...
    'VSC capability saturates outside internal-voltage limit');
t_ok(info_vv.inside_final, ...
    'VSC capability projection lands inside final feasible region');
t_is(Qv / Pv, 0.80 / 0.20, 10, ...
    'VSC radial mode preserves power factor');
[sat_v, Pp, Qp, ~, info_vq] = ...
    vsc_capability_geometry(0.20, 0.80, 1, 1, 0.5, 'preservar_p');
t_ok(sat_v && abs(Pp - 0.20) < 1e-10, ...
    'VSC preservar_p mode preserves feasible P');
t_ok(abs(Qp - info_vq.qMax) < 1e-10, ...
    'VSC preservar_p mode clips Q to feasible interval');
[~, ~, ~, ~, info_vw] = ...
    vsc_capability_curve(50, 25, 250, 1, rb.vsc(2, :), [], 1.15, rb.baseMVA);
t_is([info_vw.element_base_mva info_vw.P_original_pu ...
    info_vw.Q_original_pu info_vw.Smax_pu], [250 0.2 0.1 1], 12, ...
    'VSC capability uses own converter MVA base');
t_is(info_vw.xEq_element, info_vw.xEq_system * 250 / rb.baseMVA, 12, ...
    'VSC capability converts station reactance to own MVA base');
policy_slack = vsc_capability_policy(rb.vsc(2, :));
t_str_match(policy_slack.projection_mode, 'preservar_p', ...
    'VSC capability policy defaults DC slack to preservar_p');
t_is(policy_slack.target_ac_mode_if_saturated, c.VSC_AC_Q, 12, ...
    'VSC capability policy clips Q for DC slack voltage control');
mpcd_policy = loadcase('case5_vsc_mtdc_beerten_droop');
policy_droop = vsc_capability_policy(mpcd_policy.vsc(2, :));
t_str_match(policy_droop.projection_mode, 'preservar_p', ...
    'VSC capability policy defaults DC droop to preservar_p');
mpca_policy = loadcase('case5_vsc_mtdc_beerten_all_controls');
policy_pdc = vsc_capability_policy(mpca_policy.vsc(3, :));
t_str_match(policy_pdc.projection_mode, 'radial', ...
    'VSC capability policy defaults fixed-PDC converters to radial');
policy_pdc_override = vsc_capability_policy(mpca_policy.vsc(3, :), ...
    struct('mode', 'preservar_p'), 3, 3);
t_str_match(policy_pdc_override.reason, 'configured', ...
    'VSC capability policy reports configured projection overrides');
t_str_match(policy_pdc_override.projection_mode, 'preservar_p', ...
    'VSC capability policy lets fixed-PDC converters use configured mode');
mpc_meta = rb;
mpc_meta.vsc([1 2], c.PAC) = 60;
mpc_meta.vsc([1 2], c.QAC) = 50;
mpc_meta.vsc([1 2], c.VAC_INTERNAL) = 1;
mpc_meta.vsc_capability = struct('Snom', [70 160 150], ...
    'VconvMax', [1.15 1.15 1.15]);
cap_meta = check_vsc_capability(mpc_meta, struct('vsc_smax', 300));
t_is([cap_meta.elements(1:2).Smax], [70 160], 12, ...
    'VSC capability metadata overrides global Smax option');
t_is([cap_meta.elements(1:2).sat], [1 0], 12, ...
    'VSC capability metadata gives per-converter curves');
t_str_match(cap_meta.elements(1).Smax_source, 'metadata', ...
    'VSC capability audit reports metadata Smax source');
t_is(cap_meta.elements(1).info.xEq_element, ...
    cap_meta.elements(1).info.xEq_system * 70 / rb.baseMVA, 12, ...
    'VSC capability metadata converts station reactance to own MVA base');
mpc_vec = rmfield(mpc_meta, 'vsc_capability');
cap_vec = check_vsc_capability(mpc_vec, ...
    struct('vsc_smax', [70 160 150]));
t_is([cap_vec.elements(1:2).Smax], [70 160], 12, ...
    'VSC capability supports deterministic vector Smax options');
mpc_vmax = rb;
mpc_vmax.vsc_capability = struct('Snom', [250 250 250], ...
    'VconvMax', [1.05 1.30 1.15]);
cap_vmax = check_vsc_capability(mpc_vmax);
t_ok(cap_vmax.elements(1).info.qMax < cap_vmax.elements(2).info.qMax && ...
    strcmp(cap_vmax.elements(1).Vmax_source, 'metadata'), ...
    'VSC capability metadata VconvMax changes the converter Q range');

t_vsc_expect_error(@() vsc_capability_geometry(0, 0, 0, 1, 0.5), ...
    'Smax', 'VSC capability rejects non-positive Smax');
t_vsc_expect_error(@() vsc_capability_geometry(0, 0, 1, 0, 0.5), ...
    'V', 'VSC capability rejects non-positive voltage');
t_vsc_expect_error(@() check_vsc_capability(rb, struct('vsc_idx', 99)), ...
    'VSC index', 'VSC capability audit rejects invalid index');
t_vsc_expect_error(@() vsc_capability_geometry(0, 0, 1, 1, 0.5, 'radial', 0), ...
    'Vmax', 'VSC capability rejects invalid Vmax');
mpc_bad_meta_len = rb;
mpc_bad_meta_len.vsc_capability = struct('Snom', [250 250]);
t_vsc_expect_error(@() check_vsc_capability(mpc_bad_meta_len), ...
    'Snom has invalid length', 'VSC capability rejects malformed metadata length');
t_vsc_expect_error(@() check_vsc_capability(rb, struct('vsc_smax', [250 250])), ...
    'vsc_smax has invalid length', 'VSC capability rejects invalid option length');

cap_pf = check_capability_limits(rb);
t_is([cap_pf.count cap_pf.gen.count cap_pf.vsc.count cap_pf.violations], ...
    [5 2 3 0], 12, 'Beerten PF capability audit covers gen and VSC rows');
t_ok(isfield(cap_pf.vsc.elements, 'P_saturated') && ...
    isfield(cap_pf.gen.elements, 'active_limit'), ...
    'Beerten PF capability audit reports saturated points and limits');
t_str_match(cap_pf.gen.elements(1).active_limit, 'slack_exempt', ...
    'Beerten PF capability audit exempts slack generator');

mpcps_pf = vsc_psse_swshunt_case(mpcb);
[rpsse_sw_pf, success] = runpf_psse(mpcps_pf, mpopt_u);
t_ok(success, 'runpf_psse unified VSC-MTDC PF settles PSS/E switched shunt');
t_ok(rpsse_sw_pf.convergence.psse_controls.changed, ...
    'runpf_psse unified VSC-MTDC PF reports switched shunt active-set change');
t_is(rpsse_sw_pf.bus(5, BS), 9, 10, ...
    'runpf_psse unified VSC-MTDC PF applies switched shunt BS');
t_is(rpsse_sw_pf.psse.swshunt.num(1, 10), 9, 10, ...
    'runpf_psse unified VSC-MTDC PF syncs switched shunt BINIT');

mpcpt_pf = vsc_psse_xfmr_tap_case(mpcb);
[rpsse_tap_pf, success] = runpf_psse(mpcpt_pf, mpopt_u);
t_ok(~success, 'runpf_psse unified VSC-MTDC PF rejects infeasible transformer tap band');
t_ok(rpsse_tap_pf.convergence.psse_controls.changed, ...
    'runpf_psse unified VSC-MTDC PF reports transformer active-set change');
t_is(rpsse_tap_pf.branch(1, TAP), 0.90, 10, ...
    'runpf_psse unified VSC-MTDC PF applies transformer tap change');
t_is(rpsse_tap_pf.psse.xfmr.two.num(1, 24), 0.90, 10, ...
    'runpf_psse unified VSC-MTDC PF syncs transformer WINDV');

%%-----  VSC-MTDC continuation power flow  -----
mpct = mpcb;
mpct.bus(:, [PD QD]) = 1.10 * mpcb.bus(:, [PD QD]);
mpopt_cpf = mpoption(mpopt, 'cpf.stop_at', 1, 'cpf.step', 0.5);
t_vsc_expect_error(@() runcpf(mpcb, mpct, mpopt_cpf), ...
    'VSC-MTDC cases must be solved with runcpf_psse', ...
    'runcpf rejects VSC-MTDC cases outside PSS/E wrapper');
[rcpf, success] = runcpf_psse(mpcb, mpct, mpopt_cpf);
t_ok(success, 'runcpf_psse delegates VSC-MTDC case successfully');
t_str_match(rcpf.cpf.method, 'unified_vsc_mtdc', ...
    'runcpf_psse defaults VSC-MTDC CPF to unified method');
t_str_match(rcpf.cpf.ac_solver, 'unified', ...
    'runcpf_psse VSC-MTDC CPF uses unified PF by default');
t_str_match(rcpf.cpf.formulation, 'monolithic', ...
    'runcpf_psse unified VSC-MTDC CPF uses monolithic corrector');
t_str_match(rcpf.cpf.jacobian, 'analytic', ...
    'runcpf_psse unified VSC-MTDC CPF uses analytic Jacobian');
t_ok(size(rcpf.cpf.x, 2) == length(rcpf.cpf.lam) && ...
    size(rcpf.cpf.z, 2) == length(rcpf.cpf.lam), ...
    'runcpf_psse unified VSC-MTDC CPF stores monolithic state and tangent traces');
t_ok(size(rcpf.cpf.x, 1) > 2 * size(mpcb.bus, 1), ...
    'runcpf_psse unified VSC-MTDC CPF state includes AC/DC/VSC variables');
t_is(rcpf.cpf.max_lam, 1, 12, 'runcpf_psse VSC-MTDC reaches target lambda');
t_is(size(rcpf.cpf.V, 1), size(mpcb.bus, 1), 12, ...
    'runcpf_psse VSC-MTDC stores original AC bus voltage trace');
t_is(size(rcpf.cpf.vsc, 3), length(rcpf.cpf.lam), 12, ...
    'runcpf_psse VSC-MTDC stores VSC trace');
cap_cpf = check_capability_limits(rcpf);
t_is([cap_cpf.count cap_cpf.gen.count cap_cpf.vsc.count], [5 2 3], 12, ...
    'Beerten CPF capability audit covers gen and VSC rows');
t_is([rcpf.success cap_cpf.violations cap_cpf.gen.violations ...
        cap_cpf.vsc.violations], [1 0 0 0], 12, ...
    'Beerten CPF capability audit exempts slack generator limits');

fn_cpf = sprintf('vsc_mtdc_cpf_solvedcase_test_%d', fix(1e8*rand));
[~, success] = runcpf_vsc_mtdc(mpcb, mpct, mpopt_cpf, '', fn_cpf);
mpc_cpf_rt = loadcase(fn_cpf);
delete([fn_cpf '.m']);
t_ok(success && isfield(mpc_cpf_rt, 'busdc') && ...
    isfield(mpc_cpf_rt, 'branchdc') && isfield(mpc_cpf_rt, 'vsc'), ...
    'runcpf_vsc_mtdc solvedcase preserves VSC-MTDC fields');
[~, success] = runpf_vsc_mtdc(mpc_cpf_rt, mpopt_u);
t_ok(success, 'runcpf_vsc_mtdc solvedcase can be re-solved');

mpct_cap = mpcb;
mpct_cap.bus(:, [PD QD]) = 2 * mpcb.bus(:, [PD QD]);
policy_cap = struct('policy', 'participation', ...
    'gen_buses', 2, 'load_share', 1.0);
mpct_cap = make_cpf_gen_dispatch_target(mpcb, mpct_cap, policy_cap);
mpopt_cap = mpoption(mpopt, 'cpf.stop_at', 3, 'cpf.step', 0.1, ...
    'cpf.step_max', 0.1, 'cpf.adapt_step', 0);
mpopt_cap.vsc_mtdc.method = 'unified';
mpopt_cap.vsc_mtdc.cpf_max_lam = 20;
mpopt_cap.vsc_mtdc.cpf_max_it = 80;
mpopt_cap.vsc_mtdc.capability_enforce = 1;
mpopt_cap.vsc_mtdc.capability_vsc_smax = 250;
mpopt_cap.vsc_mtdc.capability_gen_smax = 250;
mpct_cap_pf = mpct_cap;
mpct_cap_pf.vsc_capability = struct('Snom', 70 * ones(1, size(mpct_cap.vsc, 1)));
mpopt_pf_cap = mpopt_u;
mpopt_pf_cap.vsc_mtdc.capability_enforce = 1;
mpopt_pf_cap.vsc_mtdc.capability_vsc_smax = 300;
mpopt_pf_cap.vsc_mtdc.capability_pf_max_it = 5;
[rpf_cap, success] = runpf_vsc_mtdc(mpct_cap_pf, mpopt_pf_cap);
t_ok(success, 'runpf VSC-MTDC succeeds with active VSC capability enforcement');
t_ok(rpf_cap.convergence.vsc_capability.changed && ...
    rpf_cap.convergence.vsc_capability.iterations == 2, ...
    'runpf VSC capability enforcement reports active-set iteration');
t_is(rpf_cap.vsc_capability.violations, 0, 12, ...
    'runpf VSC capability enforcement returns final point inside curve');
t_is(rpf_cap.vsc([1 2], c.AC_MODE), [c.VSC_AC_PQ; c.VSC_AC_Q], 12, ...
    'runpf VSC capability enforcement switches saturated VSC modes');
t_str_match(rpf_cap.convergence.vsc_capability.reports(1).Smax_source{1}, ...
    'metadata', 'runpf VSC capability enforcement uses case metadata');
mpopt_pf_cap_fail = mpopt_pf_cap;
mpopt_pf_cap_fail.vsc_mtdc.capability_pf_max_it = 1;
[rpf_cap_fail, success] = runpf_vsc_mtdc(mpct_cap_pf, mpopt_pf_cap_fail);
t_ok(~success && rpf_cap_fail.convergence.vsc_capability.failed, ...
    'runpf VSC capability enforcement reports max-iteration failure');
mpct_bad_cap_pf = mpct_cap_pf;
mpct_bad_cap_pf.vsc_capability = struct('Snom', [0 70 70]);
t_vsc_expect_error(@() runpf_vsc_mtdc(mpct_bad_cap_pf, mpopt_pf_cap), ...
    'VSC row 1 capability evaluation failed', ...
    'runpf VSC capability enforcement reports malformed metadata');
mpopt_cap_bad_vsc = mpopt_cap;
mpopt_cap_bad_vsc.vsc_mtdc.capability_vsc_smax = [250 250];
t_vsc_expect_error(@() runcpf_psse(mpcb, mpct_cap, mpopt_cap_bad_vsc), ...
    'capability_vsc_smax has invalid length', ...
    'runcpf_psse VSC capability enforcement reports invalid VSC option length');
mpopt_cap_bad_gen = mpopt_cap;
mpopt_cap_bad_gen.vsc_mtdc.capability_gen_smax = 0;
t_vsc_expect_error(@() runcpf_psse(mpcb, mpct_cap, mpopt_cap_bad_gen), ...
    'generator row', ...
    'runcpf_psse generator capability enforcement reports invalid generator Smax');
[rcpf_cap, success] = runcpf_psse(mpcb, mpct_cap, mpopt_cap);
t_ok(success, 'runcpf_psse VSC-MTDC succeeds with active VSC capability enforcement');
t_ok(any(strcmp({rcpf_cap.cpf.events.name}, 'GEN_CAPABILITY')), ...
    'active capability enforcement records generator saturation event');
t_ok(any(strcmp({rcpf_cap.cpf.events.name}, 'VSC_CAPABILITY')), ...
    'active VSC capability enforcement records saturation event');
gen_cap_events = rcpf_cap.cpf.events(strcmp({rcpf_cap.cpf.events.name}, ...
    'GEN_CAPABILITY'));
gen_cap_event = gen_cap_events(1);
t_ok(isfield(gen_cap_event, 'lambda_event') && ...
    isfield(gen_cap_event, 'P_candidate') && ...
    isfield(gen_cap_event, 'P_projected') && ...
    isfield(gen_cap_event, 'P_final') && ...
    isfield(gen_cap_event, 'bisection_iterations'), ...
    'active generator capability event stores location and point diagnostics');
vsc_cap_events = rcpf_cap.cpf.events(strcmp({rcpf_cap.cpf.events.name}, ...
    'VSC_CAPABILITY'));
vsc_cap_event = vsc_cap_events(1);
t_ok(isfield(vsc_cap_event, 'P_candidate') && ...
    isfield(vsc_cap_event, 'P_projected') && ...
    isfield(vsc_cap_event, 'P_final') && ...
    isfield(vsc_cap_event, 'previous_margin_error') && ...
    isfield(vsc_cap_event, 'final_error'), ...
    'active VSC capability event stores candidate, projected and final points');
t_ok(all(vsc_cap_event.lambda_event >= ...
        vsc_cap_event.lambda_previous - 1e-10) && ...
    all(vsc_cap_event.lambda_event <= ...
        vsc_cap_event.lambda_candidate + 1e-10), ...
    'active VSC capability event lambda is inside the crossing step');
lin_vsc_event = strcmp(vsc_cap_event.event_location_method, ...
    'linear_margin');
t_ok(all(isfinite(vsc_cap_event.margin_event)) && ...
    all(vsc_cap_event.margin_event <= ...
        max(vsc_cap_event.margin_previous, ...
            vsc_cap_event.margin_candidate) + 1e-8) && ...
    all(vsc_cap_event.margin_event >= ...
        min(vsc_cap_event.margin_previous, ...
            vsc_cap_event.margin_candidate) - 1e-8) && ...
    (~any(lin_vsc_event) || ...
        max(abs(vsc_cap_event.margin_event(lin_vsc_event))) < 1e-8), ...
    'active VSC capability event records true capability crossing location');
t_ok(all(vsc_cap_event.margin_candidate < 0) && ...
    all(vsc_cap_event.margin_final >= -1e-8) && ...
    all(vsc_cap_event.inside_final), ...
    'active VSC capability event records outside candidate and final feasible point');
t_str_match(vsc_cap_event.projection_mode{1}, 'preservar_p', ...
    'active VSC capability event records the resolved saturation policy');
t_is(rcpf_cap.vsc(2, c.AC_MODE), c.VSC_AC_Q, 12, ...
    'active VSC capability enforcement changes saturated voltage control to Q control');
t_ok(rcpf_cap.bus(3, VM) < 0.995, ...
    'active VSC capability enforcement releases bus-3 voltage control');
bus2_cap_gen = find(mpcb.gen(:, GEN_BUS) == 2 & ...
    mpcb.gen(:, GEN_STATUS) > 0, 1);
t_is(rcpf_cap.gen(bus2_cap_gen, [PG QG]), [200 150], 6, ...
    'active capability enforcement fixes saturated generator P and Q');
t_is(rcpf_cap.bus(2, BUS_TYPE), PQ, 12, ...
    'active capability enforcement converts saturated generator bus to PQ');
t_ok(rcpf_cap.bus(2, VM) < 0.995, ...
    'active capability enforcement releases bus-2 generator voltage control');

slack_bus = mpcb.bus(mpcb.bus(:, BUS_TYPE) == REF, BUS_I);
slack_gen = find(mpcb.gen(:, GEN_BUS) == slack_bus & ...
    mpcb.gen(:, GEN_STATUS) > 0, 1);
bus2_gen = find(mpcb.gen(:, GEN_BUS) == 2 & ...
    mpcb.gen(:, GEN_STATUS) > 0, 1);
policy_gen_bus2 = struct('policy', 'participation', ...
    'gen_buses', 2, 'load_share', 0.50);
[mpct_gen_bus2, dispatch_gen_bus2] = ...
    make_cpf_gen_dispatch_target(mpcb, mpct, policy_gen_bus2);
[rcpf_gen_bus2, success] = runcpf_psse(mpcb, mpct_gen_bus2, mpopt_cpf);
t_ok(success, 'runcpf_psse VSC-MTDC succeeds with bus-2 generator redispatch target');
t_is(dispatch_gen_bus2.gen_buses, 2, 12, ...
    'bus-2 generator redispatch audits selected generator bus');
t_is(mpct_gen_bus2.gen(bus2_gen, PG) - mpcb.gen(bus2_gen, PG), ...
    dispatch_gen_bus2.amount_mw, 12, ...
    'bus-2 generator redispatch builds expected target PG');
t_is(rcpf_gen_bus2.gen(bus2_gen, PG) - mpcb.gen(bus2_gen, PG), ...
    dispatch_gen_bus2.amount_mw, 7, ...
    'CPF reaches scheduled bus-2 generator redispatch');
t_ok(rcpf.gen(slack_gen, PG) - rcpf_gen_bus2.gen(slack_gen, PG) > ...
    0.5 * dispatch_gen_bus2.amount_mw, ...
    'bus-2 generator redispatch reduces slack active-power pickup');

mpct_share = mpct;
mpct_share.vsc(1, c.PAC_SET) = mpcb.vsc(1, c.PAC_SET) - 10;
mpct_share.vsc(3, c.PAC_SET) = mpcb.vsc(3, c.PAC_SET) + 10;
mpct_share.vsc(1, c.QAC_SET) = mpcb.vsc(1, c.QAC_SET) - 5;
mpct_share.vsc(3, c.QAC_SET) = mpcb.vsc(3, c.QAC_SET) + 3;
[rcpf_share, success] = runcpf_psse(mpcb, mpct_share, mpopt_cpf);
t_ok(success, 'runcpf_psse unified VSC-MTDC supports variable VSC set points');
t_is(rcpf_share.cpf.max_lam, 1, 12, ...
    'runcpf_psse variable VSC set points reach target lambda');
t_is(rcpf_share.vsc([1 3], c.PAC_SET), ...
    mpct_share.vsc([1 3], c.PAC_SET), 10, ...
    'runcpf_psse variable VSC active-power set points reach target values');
t_is(rcpf_share.vsc([1 3], c.PAC), ...
    mpct_share.vsc([1 3], c.PAC_SET), 7, ...
    'runcpf_psse variable VSC active powers follow target set points');
t_is(rcpf_share.vsc([1 3], c.QAC), ...
    mpct_share.vsc([1 3], c.QAC_SET), 7, ...
    'runcpf_psse variable VSC reactive powers follow target set points');
t_is(squeeze(rcpf_share.cpf.vsc([1 3], c.PAC_SET, end)), ...
    mpct_share.vsc([1 3], c.PAC_SET), 10, ...
    'runcpf_psse CPF trace stores variable VSC active-power set points');
t_ok(abs(rcpf_share.branch(5, PF)) < abs(rcpf.branch(5, PF)), ...
    'runcpf_psse variable VSC transfer reduces conventional AC branch loading');
cpf_jac_share = vsc_unified_cpf_jacobian_check(mpcb, mpct_share, mpopt_cpf);
t_ok(cpf_jac_share.dlam_abs < 2e-5 && cpf_jac_share.aug_abs < 2e-5, ...
    'unified CPF augmented Jacobian handles VSC set point transfer');

setpoint_cols = [c.PAC_SET c.QAC_SET c.VAC_SET c.PDC_SET ...
    c.VDC_SET c.KDROOP];
[mpct_constant, dispatch_const] = ...
    make_vsc_hvdc_dispatch_target(mpcb, mpct_share, 'constant');
t_is(mpct_constant.vsc(:, setpoint_cols), ...
    mpcb.vsc(:, setpoint_cols), 12, ...
    'constant VSC/HVDC dispatch keeps base VSC set points');
t_is(dispatch_const.delta_pd, sum(mpct_share.bus(:, PD) - mpcb.bus(:, PD)), ...
    12, 'constant VSC/HVDC dispatch audits active-load increment');

policy_pdc = struct( ...
    'policy',       'pdc_share_load', ...
    'hvdc_share',   0.20, ...
    'converters',   [1; 3], ...
    'weights',      [0.25; 0.75] );
[mpct_pdc, dispatch_pdc] = ...
    make_vsc_hvdc_dispatch_target(mpcb, mpct, policy_pdc);
expected_pdc = zeros(size(mpcb.vsc, 1), 1);
expected_pdc([1; 3]) = -dispatch_pdc.delta_hvdc_mw * [0.25; 0.75];
t_is(dispatch_pdc.delta_pd, 16.5, 12, ...
    'pdc_share_load audits total active-load increment');
t_is(dispatch_pdc.delta_hvdc_mw, 3.3, 12, ...
    'pdc_share_load audits scheduled HVDC share');
t_is(mpct_pdc.vsc(:, c.PDC_SET) - mpcb.vsc(:, c.PDC_SET), ...
    expected_pdc, 12, 'pdc_share_load applies expected PDC_SET deltas');
t_is(dispatch_pdc.weights_used, [0.25; 0.75], 12, ...
    'pdc_share_load audits normalized dispatch weights');

mpcd_base = loadcase('case5_vsc_mtdc_beerten_droop');
mpcd_const_target = mpcd_base;
mpcd_const_target.bus(:, [PD QD]) = 2.0 * mpcd_base.bus(:, [PD QD]);
[mpcd_const_target, ~] = ...
    make_vsc_hvdc_dispatch_target(mpcd_base, mpcd_const_target, 'constant');
mpcd_sched = loadcase('case5_vsc_mtdc_beerten_droop_target');
dispatch_d = mpcd_sched.vsc_hvdc_dispatch;
expected_droop_pdc = zeros(size(mpcd_base.vsc, 1), 1);
expected_droop_pdc([2; 3]) = -dispatch_d.delta_hvdc_mw * [0.30; 0.70];
expected_droop_qac = zeros(size(mpcd_base.vsc, 1), 1);
expected_droop_qac([1; 3]) = [1; 2];
t_is(mpcd_sched.vsc(:, c.DC_MODE), mpcd_base.vsc(:, c.DC_MODE), ...
    12, 'droop_scheduled preserves VSC DC modes');
t_ok(any(mpcd_sched.vsc(:, c.DC_MODE) == c.VSC_DC_VDC), ...
    'droop_scheduled keeps a VSC_DC_VDC reference');
t_is(mpcd_sched.vsc(:, c.PDC_SET) - mpcd_base.vsc(:, c.PDC_SET), ...
    expected_droop_pdc, 12, 'droop_scheduled applies expected PDC_SET deltas');
t_is(mpcd_sched.vsc(:, c.QAC_SET) - mpcd_base.vsc(:, c.QAC_SET), ...
    expected_droop_qac, 12, 'droop_scheduled applies expected QAC_SET deltas');
t_is(dispatch_d.converter_idx, [2; 3], 12, ...
    'droop_scheduled audits scheduled converters');
policy_qshare = struct( ...
    'policy',       'droop_scheduled', ...
    'hvdc_share',   0.02, ...
    'buses',        [3; 5], ...
    'weights',      [0.30; 0.70], ...
    'qac_policy',   'share_load', ...
    'qac_share',    0.10, ...
    'qac_buses',    [2; 5], ...
    'qac_weights',  [0.40; 0.60] );
[mpcd_qshare, dispatch_qshare] = ...
    make_vsc_hvdc_dispatch_target(mpcd_base, mpcd_const_target, policy_qshare);
expected_qshare = zeros(size(mpcd_base.vsc, 1), 1);
expected_qshare([1; 3]) = dispatch_qshare.delta_qac_mvar * [0.40; 0.60];
t_is(dispatch_qshare.delta_qd, ...
    sum(mpcd_const_target.bus(:, QD) - mpcd_base.bus(:, QD)), 12, ...
    'QAC share_load audits total reactive-load increment');
t_is(dispatch_qshare.delta_qac_mvar, 0.10 * dispatch_qshare.delta_qd, ...
    12, 'QAC share_load audits scheduled reactive support');
t_is(mpcd_qshare.vsc(:, c.QAC_SET) - mpcd_base.vsc(:, c.QAC_SET), ...
    expected_qshare, 12, 'QAC share_load applies expected QAC_SET deltas');
t_is(dispatch_qshare.qac_weights_used, [0.40; 0.60], 12, ...
    'QAC share_load audits normalized reactive weights');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcb, mpct, ...
    struct('policy', 'not_a_policy')), 'unknown policy', ...
    'VSC/HVDC dispatch rejects unknown policy');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcb, mpct, ...
    struct('policy', 'pdc_share_load', 'converters', [1; 3])), ...
    'requires HVDC_SHARE', ...
    'pdc_share_load requires hvdc_share');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcb, mpct, ...
    struct('policy', 'pdc_share_load', 'hvdc_share', 0.2)), ...
    'requires converters or buses', ...
    'pdc_share_load requires a converter selector');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcb, mpct, ...
    struct('policy', 'pdc_share_load', 'hvdc_share', 0.2, ...
    'converters', [1; 3], 'weights', [1; 2; 3])), ...
    'weights must be', ...
    'pdc_share_load rejects bad weight dimensions');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcb, mpct, ...
    struct('policy', 'pdc_share_load', 'hvdc_share', 0.2, ...
    'converters', 2)), ...
    'VSC_DC_VDC converters cannot', ...
    'pdc_share_load rejects scheduling the DC voltage slack');

mpcd_no_slack = mpcd_base;
mpcd_no_slack.vsc(1, c.DC_MODE) = c.VSC_DC_DROOP;
mpctd_no_slack = mpcd_no_slack;
mpctd_no_slack.bus(:, [PD QD]) = 2.0 * mpcd_no_slack.bus(:, [PD QD]);
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcd_no_slack, ...
    mpctd_no_slack, struct('policy', 'droop_scheduled', ...
    'hvdc_share', 0.2, 'buses', [3; 5])), ...
    'requires at least one active VSC_DC_VDC', ...
    'droop_scheduled rejects cases without a DC voltage reference');

mpcd_not_droop = mpcd_base;
mpcd_not_droop.vsc(1, c.DC_MODE) = c.VSC_DC_PDC;
mpcd_not_droop.vsc(2, c.DC_MODE) = c.VSC_DC_VDC;
mpctd_not_droop = mpcd_not_droop;
mpctd_not_droop.bus(:, [PD QD]) = 2.0 * mpcd_not_droop.bus(:, [PD QD]);
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcd_not_droop, ...
    mpctd_not_droop, struct('policy', 'droop_scheduled', ...
    'hvdc_share', 0.2, 'converters', 1)), ...
    'converters must use VSC_DC_DROOP', ...
    'droop_scheduled rejects non-droop scheduled converters');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcd_base, ...
    mpcd_const_target, struct('policy', 'droop_scheduled', ...
    'hvdc_share', 0.2, 'buses', [3; 5], 'qac_buses', [2; 5], ...
    'qac_delta', [1; 2; 3])), 'QAC deltas must match', ...
    'VSC/HVDC dispatch rejects mismatched QAC deltas');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcd_base, ...
    mpcd_const_target, struct('policy', 'droop_scheduled', ...
    'hvdc_share', 0.2, 'buses', [3; 5], 'qac_buses', 99, ...
    'qac_delta', 1)), 'no VSC converter at AC bus', ...
    'VSC/HVDC dispatch rejects unknown QAC buses');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcd_base, ...
    mpcd_const_target, struct('policy', 'droop_scheduled', ...
    'hvdc_share', 0.2, 'buses', [3; 5], ...
    'qac_policy', 'share_load', 'qac_buses', [2; 5])), ...
    'requires QAC_SHARE', ...
    'QAC share_load requires qac_share');
t_vsc_expect_error(@() make_vsc_hvdc_dispatch_target(mpcd_base, ...
    mpcd_const_target, struct('policy', 'droop_scheduled', ...
    'hvdc_share', 0.2, 'buses', [3; 5], ...
    'qac_policy', 'share_load', 'qac_share', 0.1, ...
    'qac_buses', [2; 5], 'qac_weights', [1; 2; 3])), ...
    'QAC weights must be', ...
    'QAC share_load rejects bad reactive weight dimensions');
[rcpf_d_const, success_const] = ...
    runcpf_vsc_mtdc(mpcd_base, mpcd_const_target, mpopt_cpf);
t_ok(success_const, 'runcpf_vsc_mtdc succeeds with constant Beerten droop target');
[rcpf_d_sched, success] = runcpf_vsc_mtdc(mpcd_base, mpcd_sched, mpopt_cpf);
t_ok(success, 'runcpf_vsc_mtdc succeeds with helper-built Beerten droop target');
t_ok(abs(rcpf_d_sched.branch(5, PF) - rcpf_d_const.branch(5, PF)) > 0.1, ...
    'helper-built droop dispatch measurably changes conventional AC branch loading');

mpct_api = mpcd_base;
mpct_api.bus(:, [PD QD]) = 2.0 * mpcd_base.bus(:, [PD QD]);
mpopt_dispatch = mpopt_cpf;
mpopt_dispatch.vsc_mtdc.dispatch_policy = policy_qshare;
[mpct_api_expected, dispatch_api] = ...
    make_vsc_hvdc_dispatch_target(mpcd_base, mpct_api, policy_qshare);
[rcpf_api, success] = runcpf_psse(mpcd_base, mpct_api, mpopt_dispatch);
t_ok(success, 'runcpf_psse applies VSC/HVDC dispatch policy from mpopt');
t_is(rcpf_api.vsc(:, c.PDC_SET), mpct_api_expected.vsc(:, c.PDC_SET), ...
    7, 'runcpf_psse dispatch policy reaches expected PDC_SET target');
t_is(rcpf_api.vsc(:, c.QAC_SET), mpct_api_expected.vsc(:, c.QAC_SET), ...
    7, 'runcpf_psse dispatch policy reaches expected QAC_SET target');
t_is(rcpf_api.cpf.vsc_hvdc_dispatch.delta_pdc_set, ...
    dispatch_api.delta_pdc_set, 12, ...
    'runcpf_psse CPF results audit dispatch PDC_SET deltas');
t_is(rcpf_api.cpf.vsc_hvdc_dispatch.qac_delta_set, ...
    dispatch_api.qac_delta_set, 12, ...
    'runcpf_psse CPF results audit dispatch QAC_SET deltas');
t_ok(abs(rcpf_api.branch(5, PF) - rcpf_d_const.branch(5, PF)) > 0.1, ...
    'mpopt dispatch policy measurably changes conventional AC branch loading');
args_api = struct('base', mpcd_base, 'target', mpct_api, ...
    'mpopt', mpopt_dispatch, 'lam', 0.15, 'parameterization', 3);
sys_api = vsc_cpf_internal_system(args_api);
t_is(sys_api.vsc_hvdc_dispatch.qac_delta_set, ...
    dispatch_api.qac_delta_set, 12, ...
    'internal CPF system applies mpopt VSC/HVDC dispatch policy');
args_profile_guard = struct('base', mpcb, 'target', mpct, ...
    'mpopt', mpopt_cpf, 'lam', 0.15, 'parameterization', 3);
sys_profile_guard = vsc_cpf_internal_system(args_profile_guard);
t_ok(isstruct(sys_profile_guard) && isfield(sys_profile_guard, 'A') && ...
        isfield(sys_profile_guard, 'F_aug'), ...
    'internal CPF system initializes disabled profiling before dispatch');
t_ok(~isfield(sys_profile_guard, 'timing') && ...
        ~isfield(sys_profile_guard, 'profile_timing'), ...
    'internal CPF system does not expose profiling metadata when disabled');
args_minimal = struct('base', mpcb, 'target', mpct);
sys_minimal = vsc_cpf_internal_system(args_minimal);
mpopt_default = mpoption;
t_is(sys_minimal.lam, 0, 12, ...
    'internal CPF system defaults lambda for derivative setup');
t_is(sys_minimal.z(end), 1, 12, ...
    'internal CPF system defaults tangent to lambda direction');
t_is(sys_minimal.parameterization, mpopt_default.cpf.parameterization, 12, ...
    'internal CPF system defaults CPF parameterization from mpoption');

mpca = loadcase('case5_vsc_mtdc_beerten_all_controls');
mpcta = loadcase('case5_vsc_mtdc_beerten_all_controls_target');
t_is(size(mpca.vsc, 1), 4, 12, ...
    'all-controls Beerten case has four VSC terminals');
t_is(sort(mpca.vsc(:, c.AC_MODE)), ...
    sort([c.VSC_AC_Q; c.VSC_AC_V; c.VSC_AC_PQ; c.VSC_AC_PV]), 12, ...
    'all-controls Beerten case covers all VSC AC control modes');
t_ok(all(ismember([c.VSC_DC_VDC c.VSC_DC_PDC c.VSC_DC_DROOP], ...
        mpca.vsc(:, c.DC_MODE))), ...
    'all-controls Beerten case covers all VSC DC control modes');
t_ok(isfield(mpca, 'psse') && isfield(mpca.psse, 'xfmr') && ...
        isfield(mpca.psse, 'swshunt'), ...
    'all-controls Beerten case carries PSS/E tap and shunt metadata');
[rall_pf, success] = runpf_vsc_mtdc(mpca, mpopt_u);
t_ok(success, 'all-controls Beerten VSC-MTDC PF succeeds');
t_is(max(abs(rall_pf.vsc(:, c.PAC) + rall_pf.vsc(:, c.PDC) + ...
        rall_pf.vsc(:, c.PLOSS))), 0, 7, ...
    'all-controls Beerten PF satisfies VSC power balance');
t_ok(isfield(mpcta, 'vsc_hvdc_dispatch'), ...
    'all-controls Beerten target records VSC-HVDC dispatch audit');
mpopt_all_cap = mpoption(mpopt, 'cpf.stop_at', 0.5, 'cpf.step', 0.1);
mpopt_all_cap.vsc_mtdc.method = 'unified';
mpopt_all_cap.vsc_mtdc.capability_enforce = 1;
mpopt_all_cap.vsc_mtdc.capability_vsc_smax = 250;
mpopt_all_cap.vsc_mtdc.capability_gen_smax = 250;
[rall_cpf, success] = runcpf_vsc_mtdc(mpca, mpcta, mpopt_all_cap);
t_ok(success && abs(rall_cpf.cpf.max_lam - 0.5) < 1e-6, ...
    'all-controls Beerten CPF succeeds with active capability layer');
[rall_psse_pf, success] = runpf_psse(mpca, mpopt);
t_ok(success && strcmp(rall_psse_pf.psse.pf.task_class, ...
        'unified_vsc_mtdc') && ...
        ~rall_psse_pf.convergence.psse_controls.failed && ...
        abs(rall_psse_pf.psse.swshunt.num(1, 10) - ...
        rall_psse_pf.bus(5, BS)) < 1e-10 && ...
        abs(rall_psse_pf.psse.xfmr.two.num(1, 24) - ...
        rall_psse_pf.branch(rall_psse_pf.psse.xfmr.two.branch_idx(1), TAP)) < 1e-10, ...
    'all-controls Beerten runpf_psse applies PSS/E-aware VSC-MTDC path');

mpcpap = loadcase('case5_vsc_mtdc_beerten_paper_controls_cap_explicit');
mpctpap = loadcase('case5_vsc_mtdc_beerten_paper_controls_cap_target_explicit');
t_ok(isfield(mpcpap, 'cpf_policies'), ...
    'paper-control case declares incremental CPF policies');
t_is(mpctpap.gen(:, PG), mpcpap.gen(:, PG), 12, ...
    'paper-control CPF target leaves generator dispatch at base point');
t_is(mpctpap.vsc(:, [c.PAC_SET c.QAC_SET c.PDC_SET]), ...
    mpcpap.vsc(:, [c.PAC_SET c.QAC_SET c.PDC_SET]), 12, ...
    'paper-control CPF target leaves VSC dispatch setpoints at base point');
t_is(mpctpap.bus(:, [PD QD]), 2 * mpcpap.bus(:, [PD QD]), 12, ...
    'paper-control CPF target normalizes lambda as relative load increase');
t_is(sum(mpctpap.bus(:, PD) - mpcpap.bus(:, PD)), ...
    sum(mpcpap.bus(:, PD)), 12, ...
    'paper-control CPF target adds one base-load increment per lambda');
mpcpap_k = mpcpap;
mpctpap_k = mpctpap;
mpcpap_k.cpf_policies.load.k = 0.35;
mpctpap_k.cpf_policies = mpcpap_k.cpf_policies;
[st_k, ~, ~] = vsc_mtdc_cpf_policy_state('init', mpcpap_k, ...
    mpctpap_k, struct());
lam_k1 = 0.4;
mpc_k1 = vsc_mtdc_cpf_policy_state('current_mpc', mpcpap_k, lam_k1, st_k);
dP_k1 = sum(mpcpap_k.bus(:, PD) .* st_k.load_k * lam_k1);
t_is(mpc_k1.bus(:, PD), mpcpap_k.bus(:, PD) .* ...
    (1 + lam_k1 * st_k.load_k), 12, ...
    'incremental CPF policy evaluates PD as a direct multiplicative lambda function');
t_is(mpc_k1.bus(:, QD), mpcpap_k.bus(:, QD) .* ...
    (1 + lam_k1 * st_k.load_k), 12, ...
    'incremental CPF policy evaluates QD with the same multiplicative k');
t_is(mpc_k1.gen(2, PG), mpcpap_k.gen(2, PG) + ...
    mpcpap_k.cpf_policies.gen.load_share * dP_k1, 12, ...
    'incremental CPF generator redispatch uses accepted active-load change');
t_is(mpc_k1.vsc([1 3], c.PAC_SET), ...
    [mpcpap_k.vsc(1, c.PAC_SET) - ...
        mpcpap_k.cpf_policies.hvdc.gain_mw_per_mw_load * dP_k1; ...
     mpcpap_k.vsc(3, c.PAC_SET) + ...
        mpcpap_k.cpf_policies.hvdc.gain_mw_per_mw_load * dP_k1], 12, ...
    'incremental CPF HVDC redispatch uses accepted active-load change');
t_is(mpc_k1.vsc([1 3], c.QAC_SET), mpcpap_k.vsc([1 3], c.QAC_SET) + ...
    mpcpap_k.cpf_policies.hvdc.qac_gain_mvar_per_mw_load * dP_k1, 12, ...
    'incremental CPF QAC redispatch uses accepted active-load change');
st_k.anchor_mpc = mpc_k1;
st_k.anchor_lam = lam_k1;
lam_k2 = 0.25;
mpc_k2 = vsc_mtdc_cpf_policy_state('current_mpc', mpcpap_k, lam_k2, st_k);
dP_k2 = sum(mpcpap_k.bus(:, PD) .* st_k.load_k * (lam_k2 - lam_k1));
t_is(mpc_k2.bus(:, PD), mpcpap_k.bus(:, PD) .* ...
    (1 + lam_k2 * st_k.load_k), 12, ...
    'incremental CPF load scaling remains direct when lambda decreases');
t_is(mpc_k2.bus(:, QD), mpcpap_k.bus(:, QD) .* ...
    (1 + lam_k2 * st_k.load_k), 12, ...
    'incremental CPF reactive load scaling remains direct when lambda decreases');
t_is(mpc_k2.gen(2, PG), mpc_k1.gen(2, PG) + ...
    mpcpap_k.cpf_policies.gen.load_share * dP_k2, 12, ...
    'incremental CPF generator redispatch backs off for signed active-load change');
t_is(mpc_k2.vsc([1 3], c.PAC_SET), ...
    [mpc_k1.vsc(1, c.PAC_SET) - ...
        mpcpap_k.cpf_policies.hvdc.gain_mw_per_mw_load * dP_k2; ...
     mpc_k1.vsc(3, c.PAC_SET) + ...
        mpcpap_k.cpf_policies.hvdc.gain_mw_per_mw_load * dP_k2], 12, ...
    'incremental CPF HVDC redispatch backs off for signed active-load change');
t_is(mpc_k2.vsc([1 3], c.QAC_SET), mpc_k1.vsc([1 3], c.QAC_SET) + ...
    mpcpap_k.cpf_policies.hvdc.qac_gain_mvar_per_mw_load * dP_k2, 12, ...
    'incremental CPF QAC redispatch backs off for signed active-load change');
st_k.hvdc_frozen(:) = true;
st_k.anchor_mpc = mpc_k1;
st_k.anchor_lam = lam_k1;
lam_k3 = 0.55;
mpc_k3 = vsc_mtdc_cpf_policy_state('current_mpc', mpcpap_k, lam_k3, st_k);
dP_k3 = sum(mpcpap_k.bus(:, PD) .* st_k.load_k * (lam_k3 - lam_k1));
t_is(mpc_k3.gen(2, PG), mpc_k1.gen(2, PG) + ...
    mpcpap_k.cpf_policies.gen.load_share * dP_k3, 12, ...
    'incremental CPF generator redispatch continues after HVDC freeze');
t_is(mpc_k3.vsc([1 3], c.PAC_SET), mpc_k1.vsc([1 3], c.PAC_SET), 12, ...
    'incremental CPF HVDC PAC redispatch stops after VSC capability freeze');
t_is(mpc_k3.vsc([1 3], c.QAC_SET), mpc_k1.vsc([1 3], c.QAC_SET), 12, ...
    'incremental CPF HVDC QAC redispatch stops after VSC capability freeze');
mpopt_pap_cap = mpoption(mpopt, 'cpf.stop_at', 'NOSE', ...
    'cpf.step', 0.1, 'cpf.step_min', 1e-4, 'cpf.step_max', 0.1, ...
    'cpf.adapt_step', 0, 'cpf.parameterization', 3);
mpopt_pap_cap.vsc_mtdc.method = 'unified';
mpopt_pap_cap.vsc_mtdc.cpf_max_lam = 1;
mpopt_pap_cap.vsc_mtdc.cpf_max_it = 320;
mpopt_pap_cap.vsc_mtdc.capability_enforce = 1;
mpopt_pap_cap.vsc_mtdc.capability_gen_enforce = 1;
t_vsc_expect_error(@() runcpf_vsc_mtdc(mpcpap, mpctpap, ...
    setfield(mpopt_pap_cap, 'vsc_mtdc', ...
    setfield(mpopt_pap_cap.vsc_mtdc, 'capability_limit', 'hold'))), ...
    'capability_limit', 'runcpf rejects invalid capability freeze option');
[rpap_stop, success] = runcpf_vsc_mtdc(mpcpap, mpctpap, mpopt_pap_cap);
t_ok(success, 'paper-control capability CPF stop-mode run succeeds');
t_str_match(rpap_stop.cpf.lambda_definition, 'relative_load_increase', ...
    'paper-control CPF reports typical CPF lambda convention');
t_str_match(rpap_stop.cpf.redispatch_basis, ...
    'incremental_from_previous_accepted_cpf_point', ...
    'paper-control CPF reports incremental redispatch basis');
t_ok(isfield(rpap_stop.cpf, 'vsc_hvdc_dispatch') && ...
        ~rpap_stop.cpf.vsc_hvdc_dispatch.uses_pdc_set, ...
    'paper-control HVDC redispatch does not use Pdc setpoints');
t_is(rpap_stop.cpf.gen_dispatch.load_share, 0.5, 12, ...
    'paper-control generator dispatch policy uses configured participation');
t_is(rpap_stop.cpf.vsc_hvdc_dispatch.gain_mw_per_mw_load, ...
    10 / (0.10 * sum(mpcpap.bus(:, PD))), 12, ...
    'paper-control HVDC policy is expressed as MW per MW of load increase');
t_str_match(rpap_stop.cpf.active_set_failure_policy.vsc_capability.declared_policy, ...
    'stop', 'paper-control capability CPF declares VSC stop policy');
t_str_match(rpap_stop.cpf.active_set_failure_policy.vsc_capability.observed_policy, ...
    'not-triggered', 'paper-control bounded CPF does not trigger VSC enforcement');
t_str_match(rpap_stop.cpf.active_set_failure_policy.hvdc_derating.declared_policy, ...
    'warn-and-disable', 'paper-control capability CPF declares HVDC derating policy');
t_ok(~any(strcmp({rpap_stop.cpf.events.name}, 'VSC_CAPABILITY')), ...
    'paper-control bounded CPF does not record VSC active-set saturation');
t_ok(~any(strcmp({rpap_stop.cpf.events.name}, 'VSC_CAPABILITY_FREEZE')), ...
    'paper-control capability CPF stop mode does not need recovery freeze event');
mpopt_pap_freeze = mpopt_pap_cap;
mpopt_pap_freeze.vsc_mtdc.capability_limit = 'freeze';
[rpap_freeze, success] = runcpf_vsc_mtdc(mpcpap, mpctpap, mpopt_pap_freeze);
t_ok(success, 'paper-control capability CPF freeze-mode run succeeds');
t_str_match(rpap_freeze.cpf.active_set_failure_policy.vsc_capability.declared_policy, ...
    'freeze', 'paper-control capability CPF declares VSC freeze policy');
t_ok(~any(strcmp({rpap_freeze.cpf.events.name}, ...
        'VSC_CAPABILITY_FREEZE')), ...
    'paper-control capability CPF does not freeze when active set can continue');
t_is(rpap_freeze.cpf.max_lam, rpap_stop.cpf.max_lam, 8, ...
    'paper-control capability freeze option preserves normal active-set trace');
t_ok(~any(strcmp({rpap_freeze.cpf.events.name}, 'VSC_CAPABILITY')), ...
    'paper-control freeze-mode bounded run does not record VSC saturation events');
t_ok(~isempty(strfind(rpap_freeze.cpf.done_msg, 'lambda limit')), ...
    'paper-control freeze-mode bounded regression stops by configured lambda limit');

mpcpap_full = mpcpap;
mpctpap_full = mpctpap;
mpcpap_full.cpf_policies.hvdc.policy = 'none';
mpctpap_full.cpf_policies.hvdc.policy = 'none';
mpcpap_full.explicit_options.cpf_policies.hvdc.policy = 'none';
mpctpap_full.explicit_options.cpf_policies.hvdc.policy = 'none';
mpcpap_full.cpf_policies.hvdc.vsc_derating.enabled = 0;
mpctpap_full.cpf_policies.hvdc.vsc_derating.enabled = 0;
mpcpap_full.explicit_options.cpf_policies.hvdc.vsc_derating.enabled = 0;
mpctpap_full.explicit_options.cpf_policies.hvdc.vsc_derating.enabled = 0;
mpopt_pap_full = mpoption(mpopt, 'cpf.stop_at', 'FULL', ...
    'cpf.step', 0.025, 'cpf.step_min', 1e-7, ...
    'cpf.step_max', 0.025, 'cpf.adapt_step', 1);
mpopt_pap_full.vsc_mtdc.method = 'unified';
mpopt_pap_full.vsc_mtdc.cpf_max_lam = 20;
mpopt_pap_full.vsc_mtdc.cpf_max_it = 900;
mpopt_pap_full.vsc_mtdc.capability_enforce = 1;
mpopt_pap_full.vsc_mtdc.capability_gen_enforce = 1;
mpopt_pap_full.vsc_mtdc.capability_max_it = 10;
mpopt_pap_full.vsc_mtdc.capability_limit = 'freeze';
mpopt_pap_full.vsc_mtdc.psse_control_limit = 'freeze';
[rpap_full, success] = runcpf_psse(mpcpap_full, mpctpap_full, ...
    mpopt_pap_full);
full_event_names = {};
if isfield(rpap_full.cpf, 'events') && ~isempty(rpap_full.cpf.events)
    full_event_names = {rpap_full.cpf.events.name};
end
t_ok(success && rpap_full.cpf.iterations < ...
        mpopt_pap_full.vsc_mtdc.cpf_max_it + 1 && ...
        ~isempty(strfind(rpap_full.cpf.done_msg, ...
        'VSC capability loading limit')), ...
    'paper-control FULL CPF reaches true VSC capability loading limit');
t_ok(~any(ismember(full_event_names, {'NOSE_STALL', ...
        'FULL_SWITCH_TO_VOLTAGE', 'FULL_SWITCH_TO_LAMBDA', ...
        'FULL_TRACE_LIMIT'})), ...
    'paper-control FULL CPF does not record custom VSC FULL mode events');
t_ok(~isfield(rpap_full.cpf, 'parameterization_mode') && ...
        ~isfield(rpap_full.cpf, 'voltage_bus'), ...
    'paper-control FULL CPF does not expose custom FULL state fields');
t_ok(~isfield(rpap_full.cpf, 'vsc_hvdc_dispatch') || ...
        ~rpap_full.cpf.vsc_hvdc_dispatch.uses_pdc_set, ...
    'paper-control FULL CPF keeps HVDC redispatch disabled');
% The PCC-voltage VSC capability curve is more restrictive than the previous
% internal-voltage interpretation, so this base FULL trace stops at a physical
% VSC limit instead of closing the lower branch.

mpcpgf = mpcpap;
mpctpgf = mpctpap;
mpcpgf.vsc_capability.Snom = 500 * ones(1, size(mpcpgf.vsc, 1));
mpctpgf.vsc_capability.Snom = 500 * ones(1, size(mpctpgf.vsc, 1));
mpcpgf.gen_capability.Snom = [500 90];
mpctpgf.gen_capability.Snom = [500 90];
mpctpgf.gen(2, PG) = 100;
mpopt_gen_freeze = mpopt_pap_freeze;
mpopt_gen_freeze.vsc_mtdc.cpf_max_lam = 4;
mpopt_gen_freeze.vsc_mtdc.cpf_max_it = 160;
mpopt_gen_freeze.vsc_mtdc.capability_vsc_limit = 'stop';
mpopt_gen_freeze.vsc_mtdc.capability_gen_limit = 'freeze';
mpopt_gen_freeze.vsc_mtdc.capability_gen_max_it = 1;
[rgen_freeze, success] = runcpf_vsc_mtdc(mpcpgf, mpctpgf, ...
    mpopt_gen_freeze);
t_ok(success, 'generator capability freeze-mode run succeeds');
t_str_match(rgen_freeze.cpf.active_set_failure_policy.gen_capability.declared_policy, ...
    'freeze', 'generator capability CPF declares generator freeze policy');
t_str_match(rgen_freeze.cpf.active_set_failure_policy.gen_capability.observed_policy, ...
    'freeze', 'generator capability CPF reports generator freeze');
t_ok(any(strcmp({rgen_freeze.cpf.events.name}, ...
        'GEN_CAPABILITY_FREEZE')), ...
    'generator capability freeze records freeze event');
ev_gen_freeze = rgen_freeze.cpf.events(strcmp( ...
    {rgen_freeze.cpf.events.name}, 'GEN_CAPABILITY_FREEZE'));
t_is(ev_gen_freeze(1).frozen_gen_idx, 2, 12, ...
    'generator capability freeze uses original redispatch participant');
t_ok(rgen_freeze.cpf.max_lam > ev_gen_freeze(1).lambda_freeze, ...
    'generator capability freeze continues after redispatch is frozen');

[rpsse, success] = runcpf_psse(mpcb, mpct, mpopt_cpf);
t_ok(success && strcmp(rpsse.cpf.ac_solver, 'unified') && ...
    strcmp(rpsse.psse.cpf.task_class, 'unified_vsc_mtdc'), ...
    'runcpf_psse defaults VSC-MTDC case to PSS/E-aware unified CPF');

mpcps = vsc_psse_swshunt_case(mpcb);
mpctps = mpcps;
mpctps.bus(:, [PD QD]) = 1.02 * mpcps.bus(:, [PD QD]);
mpopt_ps = mpoption(mpopt, 'cpf.stop_at', 0.2, 'cpf.step', 0.1);
[rpsse_sw, success] = runcpf_psse(mpcps, mpctps, mpopt_ps);
t_ok(success, 'runcpf_psse unified VSC-MTDC CPF settles PSS/E controls');
t_ok(length(rpsse_sw.cpf.events) >= 1, ...
    'runcpf_psse unified VSC-MTDC records PSS/E control events');
t_str_match(rpsse_sw.cpf.events(1).name, 'PSSE_CONTROL', ...
    'runcpf_psse unified VSC-MTDC labels PSS/E control event');
t_is(max([rpsse_sw.cpf.events.k]), 0, 12, ...
    'runcpf_psse unified VSC-MTDC switched shunt does not repeat at later lambdas');
t_is(rpsse_sw.bus(5, BS), 6, 10, ...
    'runcpf_psse unified VSC-MTDC applies unified-voltage switched shunt BS');
t_is(rpsse_sw.psse.swshunt.num(1, 10), 6, 10, ...
    'runcpf_psse unified VSC-MTDC syncs unified-voltage switched shunt BINIT');

mpcpt = vsc_psse_xfmr_tap_case(mpcb);
mpctpt = mpcpt;
mpctpt.bus(:, [PD QD]) = 1.02 * mpcpt.bus(:, [PD QD]);
[rpsse_tap, success] = runcpf_psse(mpcpt, mpctpt, mpopt_ps);
t_ok(~success, 'runcpf_psse unified VSC-MTDC rejects infeasible transformer tap band');
t_is(length(rpsse_tap.cpf.events), 0, 12, ...
    'runcpf_psse unified VSC-MTDC tap rejects before CPF events');
t_ok(rpsse_tap.psse.xfmr.control.below_band && ...
    ~rpsse_tap.psse.xfmr.control.inside_band, ...
    'runcpf_psse unified VSC-MTDC tap reports unsatisfied band');
t_is(rpsse_tap.branch(1, TAP), 0.90, 10, ...
    'runcpf_psse unified VSC-MTDC applies transformer tap change');
t_is(rpsse_tap.psse.xfmr.two.num(1, 24), 0.90, 10, ...
    'runcpf_psse unified VSC-MTDC syncs transformer WINDV');
t_ok(rpsse_tap.psse.xfmr.control.at_min, ...
    'runcpf_psse unified VSC-MTDC reports transformer tap limit');

mpcpg = vsc_psse_genq_case(mpcb);
mpctpg = mpcpg;
mpctpg.bus(:, [PD QD]) = 1.02 * mpcpg.bus(:, [PD QD]);
[rpsse_genq, success] = runcpf_psse(mpcpg, mpctpg, mpopt_ps);
t_ok(success, 'runcpf_psse unified VSC-MTDC settles PSS/E GENQ limit');
t_is(length(rpsse_genq.cpf.events), 1, 12, ...
    'runcpf_psse unified VSC-MTDC GENQ records one PSS/E control event');
t_str_match(rpsse_genq.cpf.events(1).name, 'PSSE_CONTROL', ...
    'runcpf_psse unified VSC-MTDC GENQ labels PSS/E control event');
t_is(rpsse_genq.cpf.events(1).k, 0, 12, ...
    'runcpf_psse unified VSC-MTDC GENQ does not repeat at later lambdas');
t_is(rpsse_genq.bus(2, BUS_TYPE), PQ, 12, ...
    'runcpf_psse unified VSC-MTDC applies GENQ bus-type change');
t_is(rpsse_genq.gen(2, QG), rpsse_genq.gen(2, QMAX), 10, ...
    'runcpf_psse unified VSC-MTDC applies GENQ QMAX limit');
t_ok(rpsse_genq.psse.genq.control.limited(2) && ...
    rpsse_genq.psse.genq.control.at_max(2), ...
    'runcpf_psse unified VSC-MTDC reports GENQ limit active set');

mpcpcl = loadcase('case5_vsc_mtdc_beerten_ultc_swshunt');
mpctpcl = mpcpcl;
mpctpcl.bus(:, [PD QD]) = 2.0 * mpcpcl.bus(:, [PD QD]);
mpopt_pcl = mpoption(mpopt, 'cpf.stop_at', 'FULL', ...
    'cpf.step', 0.05, 'cpf.step_min', 1e-4, ...
    'cpf.step_max', 0.15, 'cpf.adapt_step', 1, ...
    'cpf.parameterization', 3);
mpopt_pcl.vsc_mtdc.cpf_max_lam = 20;
mpopt_pcl.vsc_mtdc.cpf_max_it = 260;
mpopt_pcl.vsc_mtdc.psse_control_max_it = 60;
[rpsse_pcl, success] = runcpf_psse(mpcpcl, mpctpcl, mpopt_pcl);
t_ok(success, ...
    'runcpf_psse unified VSC-MTDC backs off PSS/E control failures');
t_str_match(rpsse_pcl.cpf.active_set_failure_policy.psse_control.declared_policy, ...
    'stop', 'runcpf_psse unified VSC-MTDC declares PSS/E stop policy');
t_str_match(rpsse_pcl.cpf.active_set_failure_policy.psse_control.observed_policy, ...
    'stop', 'runcpf_psse unified VSC-MTDC reports PSS/E stop');
t_str_match(rpsse_pcl.cpf.events(end).name, 'PSSE_CONTROL_LIMIT', ...
    'runcpf_psse unified VSC-MTDC reports PSS/E control loading limit');
t_ok(rpsse_pcl.cpf.max_lam > 1.34 && rpsse_pcl.cpf.max_lam < 1.35 && ...
    rpsse_pcl.bus(5, BS) == 15 && ...
    abs(rpsse_pcl.branch(rpsse_pcl.psse.xfmr.two.branch_idx, TAP) - 1.011111111111111) < 1e-10, ...
    'runcpf_psse unified VSC-MTDC locates first blocked PSS/E control limit');

mpopt_pcl_freeze = mpopt_pcl;
mpopt_pcl_freeze.vsc_mtdc.psse_control_limit = 'freeze';
[rpsse_pclf, success] = runcpf_psse(mpcpcl, mpctpcl, mpopt_pcl_freeze);
t_ok(success, ...
    'runcpf_psse unified VSC-MTDC can freeze controls after loading limit');
t_str_match(rpsse_pclf.cpf.active_set_failure_policy.psse_control.declared_policy, ...
    'freeze', 'runcpf_psse unified VSC-MTDC declares PSS/E freeze policy');
t_str_match(rpsse_pclf.cpf.active_set_failure_policy.psse_control.observed_policy, ...
    'freeze', 'runcpf_psse unified VSC-MTDC reports PSS/E freeze');
t_ok(any(strcmp({rpsse_pclf.cpf.events.name}, ...
    'PSSE_CONTROL_SELECTIVE_FREEZE')), ...
    'runcpf_psse unified VSC-MTDC records selective PSS/E control freeze event');
t_ok(rpsse_pclf.cpf.max_lam > 4.2, ...
    'runcpf_psse unified VSC-MTDC continues frozen-control PV curve');

% FACTS STATCON is a continuous Q-injection control in this harness and can
% legitimately change at each CPF point. TWODC is not mixed into the unified
% VSC-MTDC regression because the monolithic VSC equations do not include
% MATPOWER dcline state variables, so such a case would be a false contract.

mpct_nose = mpcb;
mpct_nose.bus(:, [PD QD]) = 2.0 * mpcb.bus(:, [PD QD]);
mpopt_nose = mpoption(mpopt, 'cpf.stop_at', 'NOSE', ...
    'cpf.step', 0.1, 'cpf.step_max', 0.25, 'cpf.adapt_step', 1);
mpopt_nose.vsc_mtdc.method = 'unified';
mpopt_nose.vsc_mtdc.cpf_max_lam = 20;
mpopt_nose.vsc_mtdc.cpf_max_it = 120;
[rnose, success] = runcpf_psse(mpcb, mpct_nose, mpopt_nose);
t_ok(success, 'PSS/E wrapper monolithic unified CPF reaches Beerten nose point');
t_str_match(rnose.cpf.events(1).name, 'NOSE', ...
    'monolithic unified CPF reports NOSE event');
t_ok(abs(rnose.cpf.z(end, end)) <= 10 * mpopt_nose.cpf.nose_tol, ...
    'monolithic unified CPF locates nose tangent zero');
t_ok(abs(rnose.cpf.max_lam - rnose.cpf.lam(end)) < 1e-8, ...
    'monolithic unified CPF stores nose as maximum lambda');
t_is(rnose.cpf.max_lam, 5.607430878086, 5, ...
    'monolithic unified CPF matches Beerten nose lambda benchmark');

mpopt_cpf_seq = mpopt_cpf;
mpopt_cpf_seq.vsc_mtdc.method = 'sequential';
[rpsse_seq, success] = runcpf_psse(mpcb, mpct, mpopt_cpf_seq);
t_ok(success, 'runcpf_psse delegates sequential VSC-MTDC case successfully');
t_str_match(rpsse_seq.cpf.method, 'sequential_vsc_mtdc', ...
    'runcpf_psse reports sequential VSC-MTDC CPF method when requested');
t_str_match(rpsse_seq.cpf.ac_solver, 'runpf_psse', ...
    'runcpf_psse sequential VSC-MTDC CPF uses runpf_psse AC subproblem');
t_str_match(rpsse_seq.psse.cpf.task_class, 'sequential_vsc_mtdc', ...
    'runcpf_psse reports sequential VSC-MTDC task class when requested');
t_ok(~isempty(strfind(rpsse_seq.psse.cpf.formulation, 'Sequential VSC-MTDC')), ...
    'runcpf_psse reports sequential formulation when requested');

%%-----  droop variant  -----
mpcd = mpc3;
mpcd.vsc(3, c.DC_MODE) = c.VSC_DC_DROOP;
mpcd.vsc(3, c.KDROOP) = -150;
[rd, success] = runpf_vsc_mtdc(mpcd, mpopt_seq);
t_ok(success, 'droop variant PF success');
t_is(rd.vsc(3, c.PDC), ...
    mpcd.vsc(3, c.PDC_SET) + mpcd.vsc(3, c.KDROOP) * (rd.vsc(3, c.VDC) - mpcd.vsc(3, c.VDC_SET)), ...
    8, 'droop sign convention');
t_ok(abs(rd.vsc(3, c.PDC) - mpcd.vsc(3, c.PDC_SET)) > 1e-3, ...
    'droop is optional and changes Pdc');
t_ok(rd.vsc(1, c.IS_DC_SLACK) == 1 && mpcd.vsc(1, c.DC_MODE) == c.VSC_DC_VDC, ...
    'Vdc slack remains default DC reference');
[rdu, success] = runpf_vsc_mtdc(mpcd, mpopt_u);
t_ok(success, 'droop variant unified PF success');
t_is(rdu.vsc(active3, [c.PAC c.QAC c.PDC c.VDC c.VAC_PCC c.VAC_INTERNAL c.PLOSS]), ...
    rd.vsc(active3, [c.PAC c.QAC c.PDC c.VDC c.VAC_PCC c.VAC_INTERNAL c.PLOSS]), ...
    6, 'droop variant unified VSC results match sequential solution');

%%-----  unified analytic Jacobian validation  -----
jacb = vsc_unified_jacobian_check(mpcb, mpopt_u);
t_ok(jacb.max_abs < 2e-6 && jacb.max_rel < 1e-6, ...
    'Beerten unified PF analytic Jacobian matches finite differences');
t_ok(jacb.ac_cols_abs < 2e-6, ...
    'Beerten unified PF Jacobian AC angle and voltage columns validate');
t_ok(jacb.pac_cols_abs < 1e-8, ...
    'Beerten unified PF Jacobian Pac columns validate');
t_ok(jacb.vdc_cols_abs < 1e-7, ...
    'Beerten unified PF Jacobian Vdc columns validate');
t_ok(jacb.vsc_dc_rows_abs < 2e-6, ...
    'Beerten unified PF Jacobian VSC/DC equation rows validate');

jacd = vsc_unified_jacobian_check(mpcd, mpopt_u);
t_ok(jacd.max_abs < 2e-6 && jacd.max_rel < 1e-6, ...
    'droop unified PF analytic Jacobian matches finite differences');
t_ok(jacd.ac_cols_abs < 2e-6, ...
    'droop unified PF Jacobian AC angle and voltage columns validate');
t_ok(jacd.pac_cols_abs < 1e-8, ...
    'droop unified PF Jacobian Pac columns validate');
t_ok(jacd.vdc_cols_abs < 1e-7, ...
    'droop unified PF Jacobian Vdc columns validate');
t_ok(jacd.vsc_dc_rows_abs < 2e-6, ...
    'droop unified PF Jacobian VSC/DC equation rows validate');

cpf_jac = vsc_unified_cpf_jacobian_check(mpcb, mpct, mpopt_cpf);
t_ok(cpf_jac.block_j_abs < 2e-6, ...
    'unified CPF augmented Jacobian embeds validated PF Jacobian block');
t_ok(cpf_jac.dlam_abs < 1e-8, ...
    'unified CPF dF/dlambda column matches finite differences');
t_ok(cpf_jac.param_abs < 1e-8, ...
    'unified CPF parametrization row matches finite differences');
t_ok(cpf_jac.aug_abs < 2e-6, ...
    'unified CPF augmented analytic Jacobian matches finite differences');

%%-----  convergence and excluded data/model columns  -----
t_ok(r3.convergence.max_balance < r3.convergence.tol_p, 'converged VSC balance residual');
t_ok(r3.convergence.max_delta_vdc < r3.convergence.tol_v, 'converged DC voltage change');
t_ok(r3.convergence.max_vac_ctrl_error < r3.convergence.tol_v, ...
    'converged VSC PCC voltage control error');
t_ok(~isfield(r3, 'converter') && ~isfield(r3, 'hvdc') && ~isfield(r3, 'converter_type'), ...
    'no generic converter or HVDC result fields');
idx_txt = fileread(which('idx_vsc'));
t_ok(~isfield(c, ['TR_' 'TAP']) && isempty(strfind(idx_txt, ['tr_' 'tap'])) && ...
     isempty(strfind(idx_txt, 'PMIN')) && isempty(strfind(idx_txt, 'PMAX')) && ...
     isempty(strfind(idx_txt, 'QMIN')) && isempty(strfind(idx_txt, 'QMAX')) && ...
     isempty(strfind(idx_txt, 'VDC_MIN')) && isempty(strfind(idx_txt, 'VDC_MAX')) && ...
     isempty(strfind(idx_txt, 'IMAX')) && isempty(strfind(idx_txt, 'SMAX')), ...
     'idx_vsc excludes taps and operational limit columns');

t_end;

function t_vsc_expect_error(fcn, pattern, msg)
ok = 0;
try
    fcn();
catch me
    ok = ~isempty(strfind(me.message, pattern));
end
t_ok(ok, msg);

function mpc = vsc_psse_swshunt_case(mpc)
cols = {'I', 'MODSW', 'ADJM', 'STAT', 'VSWHI', 'VSWLO', ...
    'SWREG', 'RMPCT', 'RMIDNT', 'BINIT', ...
    'N1', 'B1', 'N2', 'B2', 'N3', 'B3', 'N4', 'B4', ...
    'N5', 'B5', 'N6', 'B6', 'N7', 'B7', 'N8', 'B8', 'NREG'};
row = nan(1, 27);
row([1:8 10:12 27]) = [5 1 0 1 1.005 0.995 5 100 0 10 1 0];
mpc.psse.rev = 34;
mpc.psse.system.solver.SWSHNT = 1;
mpc.psse.system.adjust.MXTPSS = 10;
mpc.psse.swshunt = struct( ...
    'colnames', {cols}, ...
    'num', row, ...
    'txt', {cell(1, 27)}, ...
    'binit_col', 10, ...
    'status_col', 4 );

function mpc = vsc_psse_xfmr_tap_case(mpc)
[F_BUS, T_BUS, BR_R, BR_X, ~, ~, ~, ~, TAP] = idx_brch;
cols = {'I', 'J', 'K', 'CKT', 'CW', 'CZ', 'CM', 'MAG1', ...
    'MAG2', 'NMETR', 'NAME', 'STAT', 'O1', 'F1', 'O2', 'F2', ...
    'O3', 'F3', 'O4', 'F4', 'R1_2', 'X1_2', 'SBASE1_2', ...
    'WINDV1', 'NOMV1', 'ANG1', ...
    'RATE11', 'RATE21', 'RATE31', 'RATE41', 'RATE51', 'RATE61', ...
    'RATE71', 'RATE81', 'RATE91', 'RATE101', 'RATE111', 'RATE121', ...
    'COD1', 'CONT1', 'RMA1', 'RMI1', 'VMA1', 'VMI1', ...
    'NTP1', 'TAB1', 'CR1', 'CX1', 'CNXA1', 'NOD1', 'WINDV2', 'NOMV2'};
col = struct();
for k = 1:length(cols)
    col.(lower(regexprep(cols{k}, '[^A-Za-z0-9_]', '_'))) = k;
end

num = nan(1, 52);
num([1 2 3 5 6 7 12 21 22 23 24 25 26 27:38 39 40 ...
        41 42 43 44 45 46 47 48 49 50 51 52]) = ...
    [mpc.branch(1, F_BUS) mpc.branch(1, T_BUS) 0 1 1 1 1 ...
        mpc.branch(1, BR_R) mpc.branch(1, BR_X) 100 1.00 0 0 ...
        zeros(1, 12) 1 -2 1.1 0.9 1.08 1.07 5 0 0 0 0 0 1 0];
mpc.branch(1, TAP) = 1.00;
mpc.psse.rev = 34;
mpc.psse.system.solver.ACTAPS = 1;
mpc.psse.system.adjust.MXTPSS = 10;
mpc.psse.xfmr.two = struct( ...
    'colnames', {cols}, ...
    'num', num, ...
    'txt', {cell(1, 52)}, ...
    'branch_idx', 1, ...
    'col', col );
mpc.psse.xfmr.three = struct( ...
    'colnames', {{}}, ...
    'num', zeros(0, 112), ...
    'txt', {cell(0, 112)}, ...
    'branch_idx', zeros(0, 3), ...
    'col', struct() );

function mpc = vsc_psse_genq_case(mpc)
[~, ~, QG, QMAX, QMIN] = idx_gen;
mpc.gen(2, QG) = 0;
mpc.gen(2, QMAX) = -20;
mpc.gen(2, QMIN) = -100;
mpc.psse.rev = 34;
mpc.psse.system.solver.VARLIM = 1;
mpc.psse.system.adjust.MXTPSS = 10;
mpc.psse.system.newton.VCTOLQ = 0.01;
mpc.psse.genq = struct( ...
    'colnames', {{'I'}}, ...
    'num', zeros(2, 1), ...
    'txt', {cell(2, 1)}, ...
    'bus_ext', [1; 2], ...
    'reg_bus_ext', [1; 2], ...
    'status', [1; 1], ...
    'qg', [0; 0], ...
    'qmax', [500; -20], ...
    'qmin', [-500; -100], ...
    'vs', [1.06; 1.00], ...
    'rmpct', [100; 100] );

function ctx = vsc_unified_setup(mpc, mpopt)
% Test seam for private unified solver diagnostics.
ctx = runpf_vsc_mtdc_unified('__setup', mpc, mpopt);

function [F, eval] = vsc_unified_mismatch(ctx, x, Sbase)
if nargin < 3
    Sbase = [];
end
[F, eval] = runpf_vsc_mtdc_unified('__mismatch', ctx, x, Sbase);

function J = vsc_unified_jacobian(ctx, eval)
J = runpf_vsc_mtdc_unified('__jacobian', ctx, eval, []);

function sys = vsc_cpf_internal_system(args)
sys = runcpf_vsc_mtdc('__cpf_system', args);

function chk = vsc_unified_jacobian_check(mpc, mpopt)
ctx = vsc_unified_setup(mpc, mpopt);
x = ctx.x0;
[~, eval] = vsc_unified_mismatch(ctx, x, []);
J = vsc_unified_jacobian(ctx, eval);
Jfd = zeros(size(J));
for jj = 1:length(x)
    h = 1e-6 * max(1, abs(x(jj)));
    xp = x;
    xm = x;
    xp(jj) = xp(jj) + h;
    xm(jj) = xm(jj) - h;
    Fp = vsc_unified_mismatch(ctx, xp, []);
    Fm = vsc_unified_mismatch(ctx, xm, []);
    Jfd(:, jj) = (Fp - Fm) / (2 * h);
end
err = abs(J - Jfd);
rel = err ./ max(1, abs(Jfd));

nva = length(ctx.model.nonref);
nvm = length(ctx.model.vm_vars);
npac = length(ctx.model.pac_vars);
ndc = length(ctx.model.dc_var);
col_ac = [1:nva nva + (1:nvm)];
col_pac = nva + nvm + (1:npac);
col_vdc = nva + nvm + npac + (1:ndc);

row_p = 1:length(ctx.model.nonref);
row_q = length(row_p) + (1:length(ctx.model.qeq));
row_v = length(row_p) + length(row_q) + (1:length(ctx.model.vctrl));
row_bal = length(row_p) + length(row_q) + length(row_v) + ...
    (1:length(ctx.model.pac_vars));
row_dc = length(row_p) + length(row_q) + length(row_v) + ...
    length(row_bal) + (1:length(ctx.model.dc_var));
row_vsc_dc = [row_v row_bal row_dc];

chk = struct( ...
    'max_abs',        vsc_max_abs(err), ...
    'max_rel',        vsc_max_abs(rel), ...
    'ac_cols_abs',    vsc_max_abs(err(:, col_ac)), ...
    'pac_cols_abs',   vsc_max_abs(err(:, col_pac)), ...
    'vdc_cols_abs',   vsc_max_abs(err(:, col_vdc)), ...
    'vsc_dc_rows_abs', vsc_max_abs(err(row_vsc_dc, :)) );

function chk = vsc_unified_cpf_jacobian_check(mpcb, mpct, mpopt)
args = struct('base', mpcb, 'target', mpct, 'mpopt', mpopt, ...
    'lam', 0.15, 'parameterization', 3);
sys0 = vsc_cpf_internal_system(args);
nx = length(sys0.x);
z = (1:(nx + 1))';
z = z / norm(z);
h = 0.03;
x = sys0.x;
lam = args.lam;
args.x = x;
args.z = z;
args.h = h;
args.xprev = x - h * z(1:nx);
args.lamprev = lam - h * z(end);
sys = vsc_cpf_internal_system(args);

Afd = zeros(size(sys.A));
zeta = [x; lam];
for jj = 1:(nx + 1)
    step = 1e-6 * max(1, abs(zeta(jj)));
    xp = x;
    xm = x;
    lamp = lam;
    lamm = lam;
    if jj <= nx
        xp(jj) = xp(jj) + step;
        xm(jj) = xm(jj) - step;
    else
        lamp = lamp + step;
        lamm = lamm - step;
    end
    Fp = vsc_cpf_augmented_mismatch(sys.ctx, sys.Sdelta, xp, lamp, ...
        z, h, args.xprev, args.lamprev);
    Fm = vsc_cpf_augmented_mismatch(sys.ctx, sys.Sdelta, xm, lamm, ...
        z, h, args.xprev, args.lamprev);
    Afd(:, jj) = (Fp - Fm) / (2 * step);
end
err = abs(sys.A - Afd);
chk = struct( ...
    'aug_abs',     vsc_max_abs(err), ...
    'block_j_abs', vsc_max_abs(err(1:nx, 1:nx)), ...
    'dlam_abs',    vsc_max_abs(err(1:nx, end)), ...
    'param_abs',   vsc_max_abs(err(end, :)) );

function F = vsc_cpf_augmented_mismatch(ctx, Sdelta, x, lam, z, h, ...
        xprev, lamprev)
ctx_lam = vsc_cpf_test_context_at_lambda(ctx, lam);
[F0, ~] = vsc_unified_mismatch(ctx_lam, x, ctx.Sbase + lam * Sdelta);
P = z' * ([x; lam] - [xprev; lamprev]) - h;
F = [F0; P];

function ctx_lam = vsc_cpf_test_context_at_lambda(ctx, lam)
ctx_lam = ctx;
if ~isfield(ctx, 'cpf_transfer')
    return;
end
tr = ctx.cpf_transfer;
c = idx_vsc;
bdc = idx_busdc;
cols = [c.PAC_SET c.QAC_SET c.VAC_SET c.PDC_SET c.VDC_SET c.KDROOP];
mpc = tr.base;
mpc.vsc(:, cols) = tr.base.vsc(:, cols) + ...
    lam * (tr.target.vsc(:, cols) - tr.base.vsc(:, cols));
mpc.busdc(:, bdc.VDC) = tr.base.busdc(:, bdc.VDC) + ...
    lam * (tr.target.busdc(:, bdc.VDC) - tr.base.busdc(:, bdc.VDC));
ctx_lam.mpc = mpc;

function m = vsc_max_abs(x)
if isempty(x)
    m = 0;
else
    m = max(abs(x(:)));
end
